       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_330"))
implementation(project(":layer_3:module_3_311"))
implementation(project(":layer_3:module_3_336"))
implementation(project(":layer_3:module_3_345"))
implementation(project(":layer_3:module_3_403"))
implementation(project(":layer_3:module_3_384"))
implementation(project(":layer_3:module_3_288"))
implementation(project(":layer_3:module_3_392"))
implementation(project(":layer_3:module_3_349"))
implementation(project(":layer_3:module_3_321"))
implementation(project(":layer_3:module_3_327"))
implementation(project(":layer_3:module_3_333"))
implementation(project(":layer_3:module_3_331"))
implementation(project(":layer_3:module_3_391"))
implementation(project(":layer_3:module_3_275"))
implementation(project(":layer_3:module_3_326"))
implementation(project(":layer_3:module_3_394"))
implementation(project(":layer_3:module_3_262"))
implementation(project(":layer_3:module_3_279"))
implementation(project(":layer_3:module_3_371"))
implementation(project(":layer_3:module_3_363"))
implementation(project(":layer_3:module_3_368"))
implementation(project(":layer_3:module_3_261"))
implementation(project(":layer_3:module_3_367"))
implementation(project(":layer_3:module_3_314"))
implementation(project(":layer_3:module_3_381"))
implementation(project(":layer_3:module_3_357"))
implementation(project(":layer_3:module_3_274"))
implementation(project(":layer_3:module_3_342"))
implementation(project(":layer_3:module_3_370"))
implementation(project(":layer_3:module_3_323"))
implementation(project(":layer_3:module_3_297"))
implementation(project(":layer_3:module_3_322"))
implementation(project(":layer_3:module_3_347"))
implementation(project(":layer_3:module_3_380"))
implementation(project(":layer_3:module_3_378"))
implementation(project(":layer_3:module_3_396"))
implementation(project(":layer_3:module_3_351"))
implementation(project(":layer_3:module_3_376"))
implementation(project(":layer_3:module_3_337"))
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_260"))
implementation(project(":layer_3:module_3_344"))
          }
