       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_26"))
implementation(project(":layer_0:module_0_27"))
implementation(project(":layer_0:module_0_24"))
implementation(project(":layer_0:module_0_42"))
implementation(project(":layer_0:module_0_3"))
implementation(project(":layer_0:module_0_44"))
implementation(project(":layer_0:module_0_20"))
implementation(project(":layer_0:module_0_14"))
implementation(project(":layer_0:module_0_28"))
implementation(project(":layer_0:module_0_12"))
implementation(project(":layer_0:module_0_34"))
implementation(project(":layer_0:module_0_66"))
implementation(project(":layer_0:module_0_45"))
implementation(project(":layer_0:module_0_76"))
implementation(project(":layer_0:module_0_2"))
implementation(project(":layer_0:module_0_89"))
implementation(project(":layer_0:module_0_61"))
implementation(project(":layer_0:module_0_43"))
implementation(project(":layer_0:module_0_80"))
implementation(project(":layer_0:module_0_94"))
implementation(project(":layer_0:module_0_5"))
implementation(project(":layer_0:module_0_16"))
implementation(project(":layer_0:module_0_37"))
implementation(project(":layer_0:module_0_71"))
implementation(project(":layer_0:module_0_31"))
implementation(project(":layer_0:module_0_91"))
implementation(project(":layer_0:module_0_55"))
implementation(project(":layer_0:module_0_11"))
implementation(project(":layer_0:module_0_23"))
implementation(project(":layer_0:module_0_49"))
implementation(project(":layer_0:module_0_36"))
          }
