       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_371"))
implementation(project(":layer_3:module_3_260"))
implementation(project(":layer_3:module_3_258"))
implementation(project(":layer_3:module_3_353"))
implementation(project(":layer_3:module_3_286"))
implementation(project(":layer_3:module_3_382"))
implementation(project(":layer_3:module_3_317"))
implementation(project(":layer_3:module_3_270"))
implementation(project(":layer_3:module_3_360"))
implementation(project(":layer_3:module_3_387"))
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_403"))
implementation(project(":layer_3:module_3_396"))
implementation(project(":layer_3:module_3_401"))
implementation(project(":layer_3:module_3_273"))
implementation(project(":layer_3:module_3_398"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_307"))
implementation(project(":layer_3:module_3_287"))
implementation(project(":layer_3:module_3_343"))
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_295"))
implementation(project(":layer_3:module_3_266"))
implementation(project(":layer_3:module_3_268"))
implementation(project(":layer_3:module_3_358"))
implementation(project(":layer_3:module_3_397"))
implementation(project(":layer_3:module_3_282"))
implementation(project(":layer_3:module_3_256"))
implementation(project(":layer_3:module_3_306"))
implementation(project(":layer_3:module_3_275"))
implementation(project(":layer_3:module_3_285"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_375"))
implementation(project(":layer_3:module_3_324"))
implementation(project(":layer_3:module_3_293"))
implementation(project(":layer_3:module_3_305"))
implementation(project(":layer_3:module_3_349"))
implementation(project(":layer_3:module_3_345"))
implementation(project(":layer_3:module_3_303"))
implementation(project(":layer_3:module_3_393"))
implementation(project(":layer_3:module_3_381"))
implementation(project(":layer_3:module_3_347"))
implementation(project(":layer_3:module_3_315"))
implementation(project(":layer_3:module_3_309"))
implementation(project(":layer_3:module_3_392"))
implementation(project(":layer_3:module_3_402"))
          }
