       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_314"))
implementation(project(":layer_3:module_3_398"))
implementation(project(":layer_3:module_3_401"))
implementation(project(":layer_3:module_3_327"))
implementation(project(":layer_3:module_3_361"))
implementation(project(":layer_3:module_3_274"))
implementation(project(":layer_3:module_3_310"))
implementation(project(":layer_3:module_3_305"))
implementation(project(":layer_3:module_3_384"))
implementation(project(":layer_3:module_3_283"))
implementation(project(":layer_3:module_3_297"))
implementation(project(":layer_3:module_3_360"))
implementation(project(":layer_3:module_3_349"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_263"))
implementation(project(":layer_3:module_3_389"))
implementation(project(":layer_3:module_3_338"))
implementation(project(":layer_3:module_3_371"))
implementation(project(":layer_3:module_3_317"))
implementation(project(":layer_3:module_3_306"))
implementation(project(":layer_3:module_3_326"))
implementation(project(":layer_3:module_3_382"))
implementation(project(":layer_3:module_3_381"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_377"))
implementation(project(":layer_3:module_3_265"))
implementation(project(":layer_3:module_3_394"))
implementation(project(":layer_3:module_3_284"))
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_393"))
implementation(project(":layer_3:module_3_312"))
implementation(project(":layer_3:module_3_325"))
implementation(project(":layer_3:module_3_366"))
implementation(project(":layer_3:module_3_273"))
implementation(project(":layer_3:module_3_396"))
implementation(project(":layer_3:module_3_293"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_309"))
implementation(project(":layer_3:module_3_302"))
implementation(project(":layer_3:module_3_296"))
implementation(project(":layer_3:module_3_280"))
implementation(project(":layer_3:module_3_344"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_392"))
implementation(project(":layer_3:module_3_270"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_345"))
implementation(project(":layer_3:module_3_298"))
implementation(project(":layer_3:module_3_387"))
implementation(project(":layer_3:module_3_320"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_370"))
implementation(project(":layer_3:module_3_359"))
implementation(project(":layer_3:module_3_304"))
implementation(project(":layer_3:module_3_264"))
implementation(project(":layer_3:module_3_292"))
implementation(project(":layer_3:module_3_307"))
implementation(project(":layer_3:module_3_354"))
implementation(project(":layer_3:module_3_337"))
implementation(project(":layer_3:module_3_285"))
implementation(project(":layer_3:module_3_390"))
implementation(project(":layer_3:module_3_399"))
implementation(project(":layer_3:module_3_379"))
implementation(project(":layer_3:module_3_405"))
          }
