       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_193"))
implementation(project(":layer_3:module_3_201"))
implementation(project(":layer_3:module_3_203"))
implementation(project(":layer_3:module_3_175"))
implementation(project(":layer_3:module_3_174"))
implementation(project(":layer_3:module_3_221"))
implementation(project(":layer_3:module_3_199"))
implementation(project(":layer_3:module_3_218"))
implementation(project(":layer_3:module_3_176"))
implementation(project(":layer_3:module_3_206"))
implementation(project(":layer_3:module_3_207"))
implementation(project(":layer_3:module_3_216"))
implementation(project(":layer_3:module_3_188"))
implementation(project(":layer_3:module_3_170"))
implementation(project(":layer_3:module_3_214"))
implementation(project(":layer_3:module_3_234"))
implementation(project(":layer_3:module_3_225"))
implementation(project(":layer_3:module_3_211"))
implementation(project(":layer_3:module_3_191"))
implementation(project(":layer_3:module_3_171"))
implementation(project(":layer_3:module_3_184"))
implementation(project(":layer_3:module_3_158"))
implementation(project(":layer_3:module_3_213"))
implementation(project(":layer_3:module_3_196"))
implementation(project(":layer_3:module_3_167"))
implementation(project(":layer_3:module_3_182"))
          }
