       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_24"))
implementation(project(":layer_0:module_0_13"))
implementation(project(":layer_0:module_0_92"))
implementation(project(":layer_0:module_0_32"))
implementation(project(":layer_0:module_0_40"))
implementation(project(":layer_0:module_0_51"))
implementation(project(":layer_0:module_0_65"))
implementation(project(":layer_0:module_0_80"))
implementation(project(":layer_0:module_0_53"))
implementation(project(":layer_0:module_0_16"))
implementation(project(":layer_0:module_0_15"))
implementation(project(":layer_0:module_0_90"))
implementation(project(":layer_0:module_0_59"))
implementation(project(":layer_0:module_0_73"))
implementation(project(":layer_0:module_0_66"))
implementation(project(":layer_0:module_0_26"))
implementation(project(":layer_0:module_0_38"))
implementation(project(":layer_0:module_0_52"))
implementation(project(":layer_0:module_0_61"))
implementation(project(":layer_0:module_0_9"))
implementation(project(":layer_0:module_0_4"))
implementation(project(":layer_0:module_0_6"))
implementation(project(":layer_0:module_0_44"))
implementation(project(":layer_0:module_0_95"))
implementation(project(":layer_0:module_0_41"))
implementation(project(":layer_0:module_0_11"))
implementation(project(":layer_0:module_0_62"))
implementation(project(":layer_0:module_0_74"))
implementation(project(":layer_0:module_0_25"))
implementation(project(":layer_0:module_0_30"))
          }
