       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_188"))
implementation(project(":layer_3:module_3_218"))
implementation(project(":layer_3:module_3_207"))
implementation(project(":layer_3:module_3_187"))
implementation(project(":layer_3:module_3_232"))
implementation(project(":layer_3:module_3_174"))
implementation(project(":layer_3:module_3_204"))
implementation(project(":layer_3:module_3_240"))
implementation(project(":layer_3:module_3_181"))
implementation(project(":layer_3:module_3_178"))
implementation(project(":layer_3:module_3_193"))
implementation(project(":layer_3:module_3_184"))
implementation(project(":layer_3:module_3_198"))
implementation(project(":layer_3:module_3_195"))
implementation(project(":layer_3:module_3_223"))
implementation(project(":layer_3:module_3_230"))
implementation(project(":layer_3:module_3_222"))
implementation(project(":layer_3:module_3_227"))
implementation(project(":layer_3:module_3_160"))
implementation(project(":layer_3:module_3_185"))
implementation(project(":layer_3:module_3_209"))
implementation(project(":layer_3:module_3_231"))
implementation(project(":layer_3:module_3_242"))
implementation(project(":layer_3:module_3_215"))
implementation(project(":layer_3:module_3_243"))
implementation(project(":layer_3:module_3_169"))
implementation(project(":layer_3:module_3_225"))
implementation(project(":layer_3:module_3_226"))
implementation(project(":layer_3:module_3_208"))
implementation(project(":layer_3:module_3_200"))
implementation(project(":layer_3:module_3_199"))
implementation(project(":layer_3:module_3_175"))
implementation(project(":layer_3:module_3_155"))
implementation(project(":layer_3:module_3_216"))
implementation(project(":layer_3:module_3_186"))
implementation(project(":layer_3:module_3_197"))
implementation(project(":layer_3:module_3_237"))
implementation(project(":layer_3:module_3_190"))
implementation(project(":layer_3:module_3_172"))
implementation(project(":layer_3:module_3_156"))
implementation(project(":layer_3:module_3_221"))
implementation(project(":layer_3:module_3_211"))
implementation(project(":layer_3:module_3_234"))
implementation(project(":layer_3:module_3_235"))
implementation(project(":layer_3:module_3_159"))
implementation(project(":layer_3:module_3_210"))
implementation(project(":layer_3:module_3_203"))
implementation(project(":layer_3:module_3_183"))
          }
