       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_5"))
implementation(project(":layer_0:module_0_55"))
implementation(project(":layer_0:module_0_24"))
implementation(project(":layer_0:module_0_15"))
implementation(project(":layer_0:module_0_43"))
implementation(project(":layer_0:module_0_57"))
implementation(project(":layer_0:module_0_21"))
implementation(project(":layer_0:module_0_6"))
implementation(project(":layer_0:module_0_38"))
implementation(project(":layer_0:module_0_4"))
implementation(project(":layer_0:module_0_46"))
implementation(project(":layer_0:module_0_49"))
implementation(project(":layer_0:module_0_23"))
implementation(project(":layer_0:module_0_52"))
implementation(project(":layer_0:module_0_32"))
implementation(project(":layer_0:module_0_13"))
implementation(project(":layer_0:module_0_34"))
implementation(project(":layer_0:module_0_11"))
implementation(project(":layer_0:module_0_10"))
implementation(project(":layer_0:module_0_56"))
implementation(project(":layer_0:module_0_16"))
implementation(project(":layer_0:module_0_33"))
implementation(project(":layer_0:module_0_53"))
implementation(project(":layer_0:module_0_26"))
implementation(project(":layer_0:module_0_27"))
          }
