       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_52"))
implementation(project(":layer_0:module_0_68"))
implementation(project(":layer_0:module_0_84"))
implementation(project(":layer_0:module_0_82"))
implementation(project(":layer_0:module_0_92"))
implementation(project(":layer_0:module_0_78"))
implementation(project(":layer_0:module_0_28"))
implementation(project(":layer_0:module_0_58"))
implementation(project(":layer_0:module_0_24"))
implementation(project(":layer_0:module_0_4"))
implementation(project(":layer_0:module_0_80"))
implementation(project(":layer_0:module_0_8"))
implementation(project(":layer_0:module_0_38"))
implementation(project(":layer_0:module_0_74"))
implementation(project(":layer_0:module_0_35"))
implementation(project(":layer_0:module_0_73"))
implementation(project(":layer_0:module_0_91"))
implementation(project(":layer_0:module_0_1"))
implementation(project(":layer_0:module_0_37"))
implementation(project(":layer_0:module_0_16"))
implementation(project(":layer_0:module_0_39"))
implementation(project(":layer_0:module_0_25"))
implementation(project(":layer_0:module_0_94"))
implementation(project(":layer_0:module_0_14"))
implementation(project(":layer_0:module_0_41"))
implementation(project(":layer_0:module_0_26"))
implementation(project(":layer_0:module_0_77"))
implementation(project(":layer_0:module_0_18"))
implementation(project(":layer_0:module_0_69"))
implementation(project(":layer_0:module_0_55"))
          }
