       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_51"))
implementation(project(":layer_0:module_0_34"))
implementation(project(":layer_0:module_0_64"))
implementation(project(":layer_0:module_0_59"))
implementation(project(":layer_0:module_0_30"))
implementation(project(":layer_0:module_0_75"))
implementation(project(":layer_0:module_0_63"))
implementation(project(":layer_0:module_0_5"))
implementation(project(":layer_0:module_0_58"))
implementation(project(":layer_0:module_0_15"))
implementation(project(":layer_0:module_0_74"))
implementation(project(":layer_0:module_0_81"))
implementation(project(":layer_0:module_0_90"))
implementation(project(":layer_0:module_0_79"))
implementation(project(":layer_0:module_0_11"))
implementation(project(":layer_0:module_0_4"))
implementation(project(":layer_0:module_0_69"))
implementation(project(":layer_0:module_0_25"))
implementation(project(":layer_0:module_0_23"))
implementation(project(":layer_0:module_0_71"))
implementation(project(":layer_0:module_0_17"))
implementation(project(":layer_0:module_0_76"))
implementation(project(":layer_0:module_0_32"))
implementation(project(":layer_0:module_0_57"))
implementation(project(":layer_0:module_0_85"))
implementation(project(":layer_0:module_0_6"))
implementation(project(":layer_0:module_0_83"))
implementation(project(":layer_0:module_0_9"))
implementation(project(":layer_0:module_0_65"))
implementation(project(":layer_0:module_0_42"))
implementation(project(":layer_0:module_0_19"))
implementation(project(":layer_0:module_0_12"))
implementation(project(":layer_0:module_0_48"))
implementation(project(":layer_0:module_0_94"))
implementation(project(":layer_0:module_0_50"))
implementation(project(":layer_0:module_0_88"))
implementation(project(":layer_0:module_0_18"))
implementation(project(":layer_0:module_0_70"))
implementation(project(":layer_0:module_0_91"))
implementation(project(":layer_0:module_0_8"))
implementation(project(":layer_0:module_0_93"))
implementation(project(":layer_0:module_0_86"))
implementation(project(":layer_0:module_0_37"))
implementation(project(":layer_0:module_0_84"))
          }
