       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_217"))
implementation(project(":layer_3:module_3_194"))
implementation(project(":layer_3:module_3_237"))
implementation(project(":layer_3:module_3_168"))
implementation(project(":layer_3:module_3_173"))
implementation(project(":layer_3:module_3_156"))
implementation(project(":layer_3:module_3_178"))
implementation(project(":layer_3:module_3_162"))
implementation(project(":layer_3:module_3_183"))
implementation(project(":layer_3:module_3_229"))
implementation(project(":layer_3:module_3_236"))
implementation(project(":layer_3:module_3_191"))
implementation(project(":layer_3:module_3_189"))
implementation(project(":layer_3:module_3_212"))
implementation(project(":layer_3:module_3_225"))
implementation(project(":layer_3:module_3_184"))
implementation(project(":layer_3:module_3_170"))
implementation(project(":layer_3:module_3_222"))
implementation(project(":layer_3:module_3_174"))
implementation(project(":layer_3:module_3_188"))
implementation(project(":layer_3:module_3_182"))
implementation(project(":layer_3:module_3_154"))
implementation(project(":layer_3:module_3_230"))
implementation(project(":layer_3:module_3_215"))
implementation(project(":layer_3:module_3_192"))
implementation(project(":layer_3:module_3_155"))
implementation(project(":layer_3:module_3_169"))
implementation(project(":layer_3:module_3_221"))
implementation(project(":layer_3:module_3_206"))
implementation(project(":layer_3:module_3_208"))
implementation(project(":layer_3:module_3_199"))
implementation(project(":layer_3:module_3_203"))
implementation(project(":layer_3:module_3_234"))
implementation(project(":layer_3:module_3_209"))
implementation(project(":layer_3:module_3_243"))
implementation(project(":layer_3:module_3_197"))
implementation(project(":layer_3:module_3_223"))
          }
