       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_328"))
implementation(project(":layer_3:module_3_346"))
implementation(project(":layer_3:module_3_289"))
implementation(project(":layer_3:module_3_294"))
implementation(project(":layer_3:module_3_287"))
implementation(project(":layer_3:module_3_379"))
implementation(project(":layer_3:module_3_297"))
implementation(project(":layer_3:module_3_374"))
implementation(project(":layer_3:module_3_275"))
implementation(project(":layer_3:module_3_363"))
implementation(project(":layer_3:module_3_403"))
implementation(project(":layer_3:module_3_388"))
implementation(project(":layer_3:module_3_382"))
implementation(project(":layer_3:module_3_384"))
implementation(project(":layer_3:module_3_345"))
implementation(project(":layer_3:module_3_343"))
implementation(project(":layer_3:module_3_347"))
implementation(project(":layer_3:module_3_296"))
implementation(project(":layer_3:module_3_279"))
implementation(project(":layer_3:module_3_316"))
implementation(project(":layer_3:module_3_358"))
implementation(project(":layer_3:module_3_283"))
implementation(project(":layer_3:module_3_267"))
implementation(project(":layer_3:module_3_269"))
implementation(project(":layer_3:module_3_262"))
implementation(project(":layer_3:module_3_361"))
implementation(project(":layer_3:module_3_304"))
implementation(project(":layer_3:module_3_331"))
implementation(project(":layer_3:module_3_278"))
implementation(project(":layer_3:module_3_391"))
implementation(project(":layer_3:module_3_309"))
implementation(project(":layer_3:module_3_387"))
implementation(project(":layer_3:module_3_284"))
implementation(project(":layer_3:module_3_393"))
implementation(project(":layer_3:module_3_325"))
implementation(project(":layer_3:module_3_354"))
implementation(project(":layer_3:module_3_377"))
implementation(project(":layer_3:module_3_335"))
implementation(project(":layer_3:module_3_376"))
implementation(project(":layer_3:module_3_273"))
implementation(project(":layer_3:module_3_352"))
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_349"))
implementation(project(":layer_3:module_3_342"))
implementation(project(":layer_3:module_3_364"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_370"))
implementation(project(":layer_3:module_3_356"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_280"))
implementation(project(":layer_3:module_3_336"))
implementation(project(":layer_3:module_3_268"))
implementation(project(":layer_3:module_3_293"))
implementation(project(":layer_3:module_3_341"))
implementation(project(":layer_3:module_3_261"))
implementation(project(":layer_3:module_3_321"))
implementation(project(":layer_3:module_3_367"))
implementation(project(":layer_3:module_3_402"))
implementation(project(":layer_3:module_3_339"))
implementation(project(":layer_3:module_3_298"))
          }
