       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_299"))
implementation(project(":layer_3:module_3_286"))
implementation(project(":layer_3:module_3_290"))
implementation(project(":layer_3:module_3_321"))
implementation(project(":layer_3:module_3_280"))
implementation(project(":layer_3:module_3_357"))
implementation(project(":layer_3:module_3_317"))
implementation(project(":layer_3:module_3_401"))
implementation(project(":layer_3:module_3_302"))
implementation(project(":layer_3:module_3_309"))
implementation(project(":layer_3:module_3_403"))
implementation(project(":layer_3:module_3_306"))
implementation(project(":layer_3:module_3_370"))
implementation(project(":layer_3:module_3_271"))
implementation(project(":layer_3:module_3_339"))
implementation(project(":layer_3:module_3_353"))
implementation(project(":layer_3:module_3_314"))
implementation(project(":layer_3:module_3_273"))
implementation(project(":layer_3:module_3_375"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_281"))
implementation(project(":layer_3:module_3_359"))
implementation(project(":layer_3:module_3_358"))
implementation(project(":layer_3:module_3_311"))
implementation(project(":layer_3:module_3_374"))
implementation(project(":layer_3:module_3_345"))
implementation(project(":layer_3:module_3_360"))
implementation(project(":layer_3:module_3_396"))
implementation(project(":layer_3:module_3_349"))
implementation(project(":layer_3:module_3_277"))
implementation(project(":layer_3:module_3_291"))
implementation(project(":layer_3:module_3_323"))
implementation(project(":layer_3:module_3_335"))
implementation(project(":layer_3:module_3_394"))
implementation(project(":layer_3:module_3_371"))
implementation(project(":layer_3:module_3_404"))
implementation(project(":layer_3:module_3_297"))
implementation(project(":layer_3:module_3_272"))
          }
