       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_368"))
implementation(project(":layer_3:module_3_314"))
implementation(project(":layer_3:module_3_269"))
implementation(project(":layer_3:module_3_321"))
implementation(project(":layer_3:module_3_404"))
implementation(project(":layer_3:module_3_290"))
implementation(project(":layer_3:module_3_281"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_258"))
implementation(project(":layer_3:module_3_273"))
implementation(project(":layer_3:module_3_394"))
implementation(project(":layer_3:module_3_388"))
implementation(project(":layer_3:module_3_403"))
implementation(project(":layer_3:module_3_297"))
implementation(project(":layer_3:module_3_295"))
implementation(project(":layer_3:module_3_373"))
implementation(project(":layer_3:module_3_256"))
implementation(project(":layer_3:module_3_312"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_341"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_387"))
implementation(project(":layer_3:module_3_398"))
implementation(project(":layer_3:module_3_338"))
implementation(project(":layer_3:module_3_268"))
implementation(project(":layer_3:module_3_370"))
implementation(project(":layer_3:module_3_350"))
implementation(project(":layer_3:module_3_397"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_344"))
implementation(project(":layer_3:module_3_336"))
implementation(project(":layer_3:module_3_303"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_302"))
implementation(project(":layer_3:module_3_361"))
implementation(project(":layer_3:module_3_317"))
implementation(project(":layer_3:module_3_382"))
implementation(project(":layer_3:module_3_351"))
implementation(project(":layer_3:module_3_357"))
implementation(project(":layer_3:module_3_292"))
implementation(project(":layer_3:module_3_296"))
implementation(project(":layer_3:module_3_390"))
implementation(project(":layer_3:module_3_393"))
implementation(project(":layer_3:module_3_375"))
implementation(project(":layer_3:module_3_304"))
          }
