       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_305"))
implementation(project(":layer_3:module_3_289"))
implementation(project(":layer_3:module_3_321"))
implementation(project(":layer_3:module_3_331"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_402"))
implementation(project(":layer_3:module_3_279"))
implementation(project(":layer_3:module_3_281"))
implementation(project(":layer_3:module_3_369"))
implementation(project(":layer_3:module_3_290"))
implementation(project(":layer_3:module_3_291"))
implementation(project(":layer_3:module_3_335"))
implementation(project(":layer_3:module_3_345"))
implementation(project(":layer_3:module_3_380"))
implementation(project(":layer_3:module_3_382"))
implementation(project(":layer_3:module_3_337"))
implementation(project(":layer_3:module_3_372"))
implementation(project(":layer_3:module_3_396"))
implementation(project(":layer_3:module_3_325"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_330"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_375"))
implementation(project(":layer_3:module_3_367"))
implementation(project(":layer_3:module_3_292"))
implementation(project(":layer_3:module_3_280"))
implementation(project(":layer_3:module_3_263"))
implementation(project(":layer_3:module_3_357"))
implementation(project(":layer_3:module_3_363"))
implementation(project(":layer_3:module_3_404"))
implementation(project(":layer_3:module_3_347"))
implementation(project(":layer_3:module_3_308"))
implementation(project(":layer_3:module_3_362"))
implementation(project(":layer_3:module_3_355"))
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_391"))
implementation(project(":layer_3:module_3_309"))
implementation(project(":layer_3:module_3_390"))
implementation(project(":layer_3:module_3_320"))
implementation(project(":layer_3:module_3_312"))
implementation(project(":layer_3:module_3_351"))
implementation(project(":layer_3:module_3_373"))
implementation(project(":layer_3:module_3_306"))
          }
