       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_163"))
implementation(project(":layer_3:module_3_238"))
implementation(project(":layer_3:module_3_186"))
implementation(project(":layer_3:module_3_169"))
implementation(project(":layer_3:module_3_239"))
implementation(project(":layer_3:module_3_232"))
implementation(project(":layer_3:module_3_240"))
implementation(project(":layer_3:module_3_177"))
implementation(project(":layer_3:module_3_156"))
implementation(project(":layer_3:module_3_206"))
implementation(project(":layer_3:module_3_221"))
implementation(project(":layer_3:module_3_243"))
implementation(project(":layer_3:module_3_234"))
implementation(project(":layer_3:module_3_217"))
implementation(project(":layer_3:module_3_174"))
implementation(project(":layer_3:module_3_211"))
implementation(project(":layer_3:module_3_227"))
implementation(project(":layer_3:module_3_168"))
implementation(project(":layer_3:module_3_225"))
implementation(project(":layer_3:module_3_182"))
implementation(project(":layer_3:module_3_162"))
implementation(project(":layer_3:module_3_203"))
implementation(project(":layer_3:module_3_235"))
implementation(project(":layer_3:module_3_199"))
implementation(project(":layer_3:module_3_236"))
implementation(project(":layer_3:module_3_196"))
implementation(project(":layer_3:module_3_191"))
implementation(project(":layer_3:module_3_209"))
implementation(project(":layer_3:module_3_167"))
implementation(project(":layer_3:module_3_233"))
implementation(project(":layer_3:module_3_183"))
implementation(project(":layer_3:module_3_157"))
implementation(project(":layer_3:module_3_170"))
implementation(project(":layer_3:module_3_210"))
implementation(project(":layer_3:module_3_189"))
implementation(project(":layer_3:module_3_158"))
implementation(project(":layer_3:module_3_223"))
implementation(project(":layer_3:module_3_237"))
implementation(project(":layer_3:module_3_187"))
implementation(project(":layer_3:module_3_197"))
implementation(project(":layer_3:module_3_228"))
implementation(project(":layer_3:module_3_175"))
          }
