       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_220"))
implementation(project(":layer_3:module_3_196"))
implementation(project(":layer_3:module_3_240"))
implementation(project(":layer_3:module_3_242"))
implementation(project(":layer_3:module_3_181"))
implementation(project(":layer_3:module_3_222"))
implementation(project(":layer_3:module_3_160"))
implementation(project(":layer_3:module_3_190"))
implementation(project(":layer_3:module_3_217"))
implementation(project(":layer_3:module_3_218"))
implementation(project(":layer_3:module_3_234"))
implementation(project(":layer_3:module_3_166"))
implementation(project(":layer_3:module_3_165"))
implementation(project(":layer_3:module_3_193"))
implementation(project(":layer_3:module_3_169"))
implementation(project(":layer_3:module_3_191"))
implementation(project(":layer_3:module_3_225"))
implementation(project(":layer_3:module_3_197"))
implementation(project(":layer_3:module_3_216"))
implementation(project(":layer_3:module_3_202"))
implementation(project(":layer_3:module_3_210"))
implementation(project(":layer_3:module_3_201"))
implementation(project(":layer_3:module_3_163"))
implementation(project(":layer_3:module_3_199"))
implementation(project(":layer_3:module_3_208"))
implementation(project(":layer_3:module_3_229"))
implementation(project(":layer_3:module_3_238"))
implementation(project(":layer_3:module_3_213"))
implementation(project(":layer_3:module_3_215"))
implementation(project(":layer_3:module_3_178"))
          }
