       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_335"))
implementation(project(":layer_3:module_3_331"))
implementation(project(":layer_3:module_3_268"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_393"))
implementation(project(":layer_3:module_3_315"))
implementation(project(":layer_3:module_3_371"))
implementation(project(":layer_3:module_3_325"))
implementation(project(":layer_3:module_3_288"))
implementation(project(":layer_3:module_3_332"))
implementation(project(":layer_3:module_3_263"))
implementation(project(":layer_3:module_3_310"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_286"))
implementation(project(":layer_3:module_3_338"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_294"))
implementation(project(":layer_3:module_3_298"))
implementation(project(":layer_3:module_3_385"))
implementation(project(":layer_3:module_3_372"))
implementation(project(":layer_3:module_3_366"))
implementation(project(":layer_3:module_3_266"))
implementation(project(":layer_3:module_3_346"))
implementation(project(":layer_3:module_3_394"))
implementation(project(":layer_3:module_3_345"))
implementation(project(":layer_3:module_3_361"))
implementation(project(":layer_3:module_3_377"))
implementation(project(":layer_3:module_3_296"))
implementation(project(":layer_3:module_3_290"))
implementation(project(":layer_3:module_3_289"))
implementation(project(":layer_3:module_3_350"))
implementation(project(":layer_3:module_3_329"))
implementation(project(":layer_3:module_3_300"))
implementation(project(":layer_3:module_3_309"))
implementation(project(":layer_3:module_3_267"))
implementation(project(":layer_3:module_3_319"))
          }
