       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_269"))
implementation(project(":layer_3:module_3_326"))
implementation(project(":layer_3:module_3_267"))
implementation(project(":layer_3:module_3_315"))
implementation(project(":layer_3:module_3_297"))
implementation(project(":layer_3:module_3_341"))
implementation(project(":layer_3:module_3_304"))
implementation(project(":layer_3:module_3_275"))
implementation(project(":layer_3:module_3_295"))
implementation(project(":layer_3:module_3_337"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_273"))
implementation(project(":layer_3:module_3_324"))
implementation(project(":layer_3:module_3_363"))
implementation(project(":layer_3:module_3_289"))
implementation(project(":layer_3:module_3_279"))
implementation(project(":layer_3:module_3_372"))
implementation(project(":layer_3:module_3_361"))
implementation(project(":layer_3:module_3_257"))
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_375"))
implementation(project(":layer_3:module_3_390"))
implementation(project(":layer_3:module_3_306"))
implementation(project(":layer_3:module_3_351"))
implementation(project(":layer_3:module_3_378"))
implementation(project(":layer_3:module_3_264"))
implementation(project(":layer_3:module_3_258"))
implementation(project(":layer_3:module_3_398"))
implementation(project(":layer_3:module_3_347"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_272"))
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_280"))
          }
