       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_322"))
implementation(project(":layer_3:module_3_311"))
implementation(project(":layer_3:module_3_265"))
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_385"))
implementation(project(":layer_3:module_3_317"))
implementation(project(":layer_3:module_3_272"))
implementation(project(":layer_3:module_3_370"))
implementation(project(":layer_3:module_3_388"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_306"))
implementation(project(":layer_3:module_3_382"))
implementation(project(":layer_3:module_3_343"))
implementation(project(":layer_3:module_3_342"))
implementation(project(":layer_3:module_3_402"))
implementation(project(":layer_3:module_3_387"))
implementation(project(":layer_3:module_3_357"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_375"))
implementation(project(":layer_3:module_3_392"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_364"))
implementation(project(":layer_3:module_3_389"))
implementation(project(":layer_3:module_3_378"))
implementation(project(":layer_3:module_3_326"))
implementation(project(":layer_3:module_3_350"))
implementation(project(":layer_3:module_3_260"))
implementation(project(":layer_3:module_3_346"))
implementation(project(":layer_3:module_3_312"))
implementation(project(":layer_3:module_3_290"))
implementation(project(":layer_3:module_3_277"))
implementation(project(":layer_3:module_3_304"))
implementation(project(":layer_3:module_3_384"))
implementation(project(":layer_3:module_3_337"))
implementation(project(":layer_3:module_3_327"))
implementation(project(":layer_3:module_3_363"))
implementation(project(":layer_3:module_3_300"))
implementation(project(":layer_3:module_3_404"))
implementation(project(":layer_3:module_3_397"))
implementation(project(":layer_3:module_3_339"))
implementation(project(":layer_3:module_3_367"))
implementation(project(":layer_3:module_3_376"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_283"))
implementation(project(":layer_3:module_3_305"))
implementation(project(":layer_3:module_3_294"))
implementation(project(":layer_3:module_3_381"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_280"))
implementation(project(":layer_3:module_3_405"))
implementation(project(":layer_3:module_3_324"))
implementation(project(":layer_3:module_3_379"))
          }
