       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_373"))
implementation(project(":layer_3:module_3_363"))
implementation(project(":layer_3:module_3_337"))
implementation(project(":layer_3:module_3_271"))
implementation(project(":layer_3:module_3_331"))
implementation(project(":layer_3:module_3_401"))
implementation(project(":layer_3:module_3_370"))
implementation(project(":layer_3:module_3_339"))
implementation(project(":layer_3:module_3_317"))
implementation(project(":layer_3:module_3_268"))
implementation(project(":layer_3:module_3_376"))
implementation(project(":layer_3:module_3_403"))
implementation(project(":layer_3:module_3_292"))
implementation(project(":layer_3:module_3_265"))
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_393"))
implementation(project(":layer_3:module_3_287"))
implementation(project(":layer_3:module_3_371"))
implementation(project(":layer_3:module_3_353"))
implementation(project(":layer_3:module_3_263"))
implementation(project(":layer_3:module_3_295"))
implementation(project(":layer_3:module_3_398"))
implementation(project(":layer_3:module_3_405"))
implementation(project(":layer_3:module_3_299"))
implementation(project(":layer_3:module_3_387"))
implementation(project(":layer_3:module_3_349"))
implementation(project(":layer_3:module_3_278"))
implementation(project(":layer_3:module_3_378"))
implementation(project(":layer_3:module_3_312"))
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_320"))
implementation(project(":layer_3:module_3_306"))
implementation(project(":layer_3:module_3_298"))
implementation(project(":layer_3:module_3_402"))
implementation(project(":layer_3:module_3_262"))
implementation(project(":layer_3:module_3_284"))
implementation(project(":layer_3:module_3_382"))
implementation(project(":layer_3:module_3_342"))
implementation(project(":layer_3:module_3_274"))
implementation(project(":layer_3:module_3_394"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_314"))
implementation(project(":layer_3:module_3_281"))
implementation(project(":layer_3:module_3_294"))
implementation(project(":layer_3:module_3_334"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_307"))
implementation(project(":layer_3:module_3_379"))
implementation(project(":layer_3:module_3_352"))
implementation(project(":layer_3:module_3_315"))
implementation(project(":layer_3:module_3_332"))
implementation(project(":layer_3:module_3_308"))
implementation(project(":layer_3:module_3_367"))
implementation(project(":layer_3:module_3_335"))
implementation(project(":layer_3:module_3_313"))
implementation(project(":layer_3:module_3_347"))
implementation(project(":layer_3:module_3_316"))
          }
