       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_256"))
implementation(project(":layer_3:module_3_265"))
implementation(project(":layer_3:module_3_266"))
implementation(project(":layer_3:module_3_275"))
implementation(project(":layer_3:module_3_311"))
implementation(project(":layer_3:module_3_343"))
implementation(project(":layer_3:module_3_350"))
implementation(project(":layer_3:module_3_392"))
implementation(project(":layer_3:module_3_319"))
implementation(project(":layer_3:module_3_333"))
implementation(project(":layer_3:module_3_402"))
implementation(project(":layer_3:module_3_342"))
implementation(project(":layer_3:module_3_370"))
implementation(project(":layer_3:module_3_380"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_327"))
implementation(project(":layer_3:module_3_368"))
implementation(project(":layer_3:module_3_345"))
implementation(project(":layer_3:module_3_357"))
implementation(project(":layer_3:module_3_369"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_298"))
implementation(project(":layer_3:module_3_286"))
implementation(project(":layer_3:module_3_328"))
implementation(project(":layer_3:module_3_360"))
implementation(project(":layer_3:module_3_279"))
implementation(project(":layer_3:module_3_334"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_339"))
implementation(project(":layer_3:module_3_386"))
implementation(project(":layer_3:module_3_267"))
implementation(project(":layer_3:module_3_364"))
implementation(project(":layer_3:module_3_384"))
implementation(project(":layer_3:module_3_335"))
implementation(project(":layer_3:module_3_395"))
implementation(project(":layer_3:module_3_305"))
implementation(project(":layer_3:module_3_405"))
implementation(project(":layer_3:module_3_352"))
          }
