       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_277"))
implementation(project(":layer_3:module_3_269"))
implementation(project(":layer_3:module_3_306"))
implementation(project(":layer_3:module_3_353"))
implementation(project(":layer_3:module_3_372"))
implementation(project(":layer_3:module_3_274"))
implementation(project(":layer_3:module_3_346"))
implementation(project(":layer_3:module_3_396"))
implementation(project(":layer_3:module_3_373"))
implementation(project(":layer_3:module_3_374"))
implementation(project(":layer_3:module_3_391"))
implementation(project(":layer_3:module_3_352"))
implementation(project(":layer_3:module_3_388"))
implementation(project(":layer_3:module_3_393"))
implementation(project(":layer_3:module_3_335"))
implementation(project(":layer_3:module_3_265"))
implementation(project(":layer_3:module_3_332"))
implementation(project(":layer_3:module_3_282"))
implementation(project(":layer_3:module_3_377"))
implementation(project(":layer_3:module_3_302"))
implementation(project(":layer_3:module_3_385"))
implementation(project(":layer_3:module_3_256"))
implementation(project(":layer_3:module_3_322"))
implementation(project(":layer_3:module_3_354"))
implementation(project(":layer_3:module_3_283"))
implementation(project(":layer_3:module_3_331"))
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_366"))
implementation(project(":layer_3:module_3_337"))
implementation(project(":layer_3:module_3_330"))
implementation(project(":layer_3:module_3_317"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_325"))
implementation(project(":layer_3:module_3_314"))
implementation(project(":layer_3:module_3_312"))
implementation(project(":layer_3:module_3_300"))
implementation(project(":layer_3:module_3_262"))
implementation(project(":layer_3:module_3_392"))
implementation(project(":layer_3:module_3_290"))
implementation(project(":layer_3:module_3_292"))
implementation(project(":layer_3:module_3_384"))
implementation(project(":layer_3:module_3_351"))
implementation(project(":layer_3:module_3_268"))
implementation(project(":layer_3:module_3_285"))
implementation(project(":layer_3:module_3_382"))
implementation(project(":layer_3:module_3_297"))
implementation(project(":layer_3:module_3_272"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_313"))
implementation(project(":layer_3:module_3_336"))
implementation(project(":layer_3:module_3_349"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_386"))
implementation(project(":layer_3:module_3_323"))
implementation(project(":layer_3:module_3_358"))
implementation(project(":layer_3:module_3_280"))
implementation(project(":layer_3:module_3_309"))
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_398"))
implementation(project(":layer_3:module_3_270"))
implementation(project(":layer_3:module_3_298"))
implementation(project(":layer_3:module_3_390"))
implementation(project(":layer_3:module_3_310"))
          }
