       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_367"))
implementation(project(":layer_3:module_3_291"))
implementation(project(":layer_3:module_3_402"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_315"))
implementation(project(":layer_3:module_3_370"))
implementation(project(":layer_3:module_3_295"))
implementation(project(":layer_3:module_3_356"))
implementation(project(":layer_3:module_3_344"))
implementation(project(":layer_3:module_3_264"))
implementation(project(":layer_3:module_3_330"))
implementation(project(":layer_3:module_3_299"))
implementation(project(":layer_3:module_3_261"))
implementation(project(":layer_3:module_3_292"))
implementation(project(":layer_3:module_3_405"))
implementation(project(":layer_3:module_3_272"))
implementation(project(":layer_3:module_3_354"))
implementation(project(":layer_3:module_3_322"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_283"))
implementation(project(":layer_3:module_3_323"))
implementation(project(":layer_3:module_3_347"))
implementation(project(":layer_3:module_3_361"))
implementation(project(":layer_3:module_3_313"))
implementation(project(":layer_3:module_3_305"))
implementation(project(":layer_3:module_3_401"))
implementation(project(":layer_3:module_3_359"))
implementation(project(":layer_3:module_3_304"))
implementation(project(":layer_3:module_3_296"))
implementation(project(":layer_3:module_3_368"))
implementation(project(":layer_3:module_3_314"))
implementation(project(":layer_3:module_3_363"))
implementation(project(":layer_3:module_3_298"))
implementation(project(":layer_3:module_3_352"))
implementation(project(":layer_3:module_3_328"))
implementation(project(":layer_3:module_3_321"))
implementation(project(":layer_3:module_3_396"))
implementation(project(":layer_3:module_3_345"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_311"))
implementation(project(":layer_3:module_3_303"))
implementation(project(":layer_3:module_3_312"))
implementation(project(":layer_3:module_3_267"))
implementation(project(":layer_3:module_3_369"))
implementation(project(":layer_3:module_3_374"))
implementation(project(":layer_3:module_3_392"))
implementation(project(":layer_3:module_3_362"))
          }
