       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_240"))
implementation(project(":layer_3:module_3_228"))
implementation(project(":layer_3:module_3_156"))
implementation(project(":layer_3:module_3_208"))
implementation(project(":layer_3:module_3_203"))
implementation(project(":layer_3:module_3_175"))
implementation(project(":layer_3:module_3_174"))
implementation(project(":layer_3:module_3_169"))
implementation(project(":layer_3:module_3_173"))
implementation(project(":layer_3:module_3_161"))
implementation(project(":layer_3:module_3_197"))
implementation(project(":layer_3:module_3_155"))
implementation(project(":layer_3:module_3_222"))
implementation(project(":layer_3:module_3_232"))
implementation(project(":layer_3:module_3_238"))
implementation(project(":layer_3:module_3_185"))
implementation(project(":layer_3:module_3_172"))
implementation(project(":layer_3:module_3_209"))
implementation(project(":layer_3:module_3_164"))
implementation(project(":layer_3:module_3_191"))
implementation(project(":layer_3:module_3_168"))
implementation(project(":layer_3:module_3_201"))
implementation(project(":layer_3:module_3_210"))
implementation(project(":layer_3:module_3_186"))
implementation(project(":layer_3:module_3_224"))
implementation(project(":layer_3:module_3_167"))
implementation(project(":layer_3:module_3_171"))
implementation(project(":layer_3:module_3_218"))
implementation(project(":layer_3:module_3_195"))
implementation(project(":layer_3:module_3_160"))
implementation(project(":layer_3:module_3_177"))
implementation(project(":layer_3:module_3_158"))
implementation(project(":layer_3:module_3_216"))
implementation(project(":layer_3:module_3_182"))
implementation(project(":layer_3:module_3_234"))
implementation(project(":layer_3:module_3_190"))
implementation(project(":layer_3:module_3_225"))
          }
