       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_185"))
implementation(project(":layer_3:module_3_237"))
implementation(project(":layer_3:module_3_178"))
implementation(project(":layer_3:module_3_230"))
implementation(project(":layer_3:module_3_205"))
implementation(project(":layer_3:module_3_198"))
implementation(project(":layer_3:module_3_163"))
implementation(project(":layer_3:module_3_155"))
implementation(project(":layer_3:module_3_191"))
implementation(project(":layer_3:module_3_226"))
implementation(project(":layer_3:module_3_208"))
implementation(project(":layer_3:module_3_188"))
implementation(project(":layer_3:module_3_225"))
implementation(project(":layer_3:module_3_158"))
implementation(project(":layer_3:module_3_212"))
implementation(project(":layer_3:module_3_239"))
implementation(project(":layer_3:module_3_203"))
implementation(project(":layer_3:module_3_193"))
implementation(project(":layer_3:module_3_234"))
implementation(project(":layer_3:module_3_157"))
implementation(project(":layer_3:module_3_166"))
implementation(project(":layer_3:module_3_233"))
implementation(project(":layer_3:module_3_200"))
implementation(project(":layer_3:module_3_154"))
implementation(project(":layer_3:module_3_231"))
implementation(project(":layer_3:module_3_175"))
implementation(project(":layer_3:module_3_182"))
implementation(project(":layer_3:module_3_181"))
implementation(project(":layer_3:module_3_161"))
implementation(project(":layer_3:module_3_221"))
implementation(project(":layer_3:module_3_219"))
implementation(project(":layer_3:module_3_180"))
implementation(project(":layer_3:module_3_162"))
implementation(project(":layer_3:module_3_197"))
implementation(project(":layer_3:module_3_210"))
implementation(project(":layer_3:module_3_177"))
implementation(project(":layer_3:module_3_187"))
          }
