       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_51"))
implementation(project(":layer_0:module_0_33"))
implementation(project(":layer_0:module_0_32"))
implementation(project(":layer_0:module_0_35"))
implementation(project(":layer_0:module_0_19"))
implementation(project(":layer_0:module_0_39"))
implementation(project(":layer_0:module_0_12"))
implementation(project(":layer_0:module_0_13"))
implementation(project(":layer_0:module_0_17"))
implementation(project(":layer_0:module_0_26"))
implementation(project(":layer_0:module_0_55"))
implementation(project(":layer_0:module_0_27"))
implementation(project(":layer_0:module_0_44"))
implementation(project(":layer_0:module_0_2"))
implementation(project(":layer_0:module_0_36"))
implementation(project(":layer_0:module_0_4"))
implementation(project(":layer_0:module_0_52"))
implementation(project(":layer_0:module_0_23"))
implementation(project(":layer_0:module_0_10"))
implementation(project(":layer_0:module_0_41"))
implementation(project(":layer_0:module_0_46"))
implementation(project(":layer_0:module_0_7"))
implementation(project(":layer_0:module_0_11"))
implementation(project(":layer_0:module_0_16"))
implementation(project(":layer_0:module_0_31"))
implementation(project(":layer_0:module_0_5"))
implementation(project(":layer_0:module_0_56"))
implementation(project(":layer_0:module_0_8"))
implementation(project(":layer_0:module_0_40"))
implementation(project(":layer_0:module_0_38"))
implementation(project(":layer_0:module_0_24"))
          }
