       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_161"))
implementation(project(":layer_3:module_3_165"))
implementation(project(":layer_3:module_3_162"))
implementation(project(":layer_3:module_3_212"))
implementation(project(":layer_3:module_3_186"))
implementation(project(":layer_3:module_3_163"))
implementation(project(":layer_3:module_3_173"))
implementation(project(":layer_3:module_3_182"))
implementation(project(":layer_3:module_3_232"))
implementation(project(":layer_3:module_3_170"))
implementation(project(":layer_3:module_3_156"))
implementation(project(":layer_3:module_3_210"))
implementation(project(":layer_3:module_3_187"))
implementation(project(":layer_3:module_3_227"))
implementation(project(":layer_3:module_3_158"))
implementation(project(":layer_3:module_3_193"))
implementation(project(":layer_3:module_3_240"))
implementation(project(":layer_3:module_3_216"))
implementation(project(":layer_3:module_3_154"))
implementation(project(":layer_3:module_3_206"))
implementation(project(":layer_3:module_3_197"))
implementation(project(":layer_3:module_3_179"))
implementation(project(":layer_3:module_3_226"))
implementation(project(":layer_3:module_3_155"))
implementation(project(":layer_3:module_3_228"))
implementation(project(":layer_3:module_3_191"))
implementation(project(":layer_3:module_3_215"))
implementation(project(":layer_3:module_3_211"))
implementation(project(":layer_3:module_3_224"))
implementation(project(":layer_3:module_3_220"))
implementation(project(":layer_3:module_3_178"))
implementation(project(":layer_3:module_3_203"))
implementation(project(":layer_3:module_3_207"))
implementation(project(":layer_3:module_3_236"))
implementation(project(":layer_3:module_3_180"))
implementation(project(":layer_3:module_3_239"))
implementation(project(":layer_3:module_3_198"))
implementation(project(":layer_3:module_3_177"))
implementation(project(":layer_3:module_3_188"))
implementation(project(":layer_3:module_3_157"))
implementation(project(":layer_3:module_3_229"))
implementation(project(":layer_3:module_3_200"))
          }
