       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_310"))
implementation(project(":layer_3:module_3_279"))
implementation(project(":layer_3:module_3_293"))
implementation(project(":layer_3:module_3_308"))
implementation(project(":layer_3:module_3_341"))
implementation(project(":layer_3:module_3_355"))
implementation(project(":layer_3:module_3_339"))
implementation(project(":layer_3:module_3_295"))
implementation(project(":layer_3:module_3_261"))
implementation(project(":layer_3:module_3_403"))
implementation(project(":layer_3:module_3_322"))
implementation(project(":layer_3:module_3_397"))
implementation(project(":layer_3:module_3_274"))
implementation(project(":layer_3:module_3_264"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_370"))
implementation(project(":layer_3:module_3_314"))
implementation(project(":layer_3:module_3_300"))
implementation(project(":layer_3:module_3_393"))
implementation(project(":layer_3:module_3_278"))
implementation(project(":layer_3:module_3_376"))
implementation(project(":layer_3:module_3_292"))
implementation(project(":layer_3:module_3_265"))
implementation(project(":layer_3:module_3_353"))
implementation(project(":layer_3:module_3_387"))
implementation(project(":layer_3:module_3_266"))
implementation(project(":layer_3:module_3_389"))
implementation(project(":layer_3:module_3_373"))
implementation(project(":layer_3:module_3_282"))
implementation(project(":layer_3:module_3_359"))
implementation(project(":layer_3:module_3_396"))
implementation(project(":layer_3:module_3_315"))
implementation(project(":layer_3:module_3_402"))
implementation(project(":layer_3:module_3_288"))
implementation(project(":layer_3:module_3_398"))
implementation(project(":layer_3:module_3_358"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_304"))
implementation(project(":layer_3:module_3_269"))
implementation(project(":layer_3:module_3_281"))
implementation(project(":layer_3:module_3_333"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_344"))
          }
