       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_285"))
implementation(project(":layer_3:module_3_330"))
implementation(project(":layer_3:module_3_404"))
implementation(project(":layer_3:module_3_325"))
implementation(project(":layer_3:module_3_314"))
implementation(project(":layer_3:module_3_355"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_309"))
implementation(project(":layer_3:module_3_275"))
implementation(project(":layer_3:module_3_305"))
implementation(project(":layer_3:module_3_291"))
implementation(project(":layer_3:module_3_364"))
implementation(project(":layer_3:module_3_308"))
implementation(project(":layer_3:module_3_331"))
implementation(project(":layer_3:module_3_338"))
implementation(project(":layer_3:module_3_313"))
implementation(project(":layer_3:module_3_302"))
implementation(project(":layer_3:module_3_344"))
implementation(project(":layer_3:module_3_389"))
implementation(project(":layer_3:module_3_289"))
implementation(project(":layer_3:module_3_388"))
implementation(project(":layer_3:module_3_405"))
implementation(project(":layer_3:module_3_349"))
implementation(project(":layer_3:module_3_394"))
implementation(project(":layer_3:module_3_384"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_299"))
implementation(project(":layer_3:module_3_315"))
implementation(project(":layer_3:module_3_290"))
implementation(project(":layer_3:module_3_379"))
implementation(project(":layer_3:module_3_257"))
implementation(project(":layer_3:module_3_376"))
implementation(project(":layer_3:module_3_260"))
implementation(project(":layer_3:module_3_295"))
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_322"))
implementation(project(":layer_3:module_3_306"))
implementation(project(":layer_3:module_3_261"))
implementation(project(":layer_3:module_3_310"))
implementation(project(":layer_3:module_3_346"))
implementation(project(":layer_3:module_3_386"))
implementation(project(":layer_3:module_3_374"))
implementation(project(":layer_3:module_3_304"))
implementation(project(":layer_3:module_3_337"))
implementation(project(":layer_3:module_3_277"))
implementation(project(":layer_3:module_3_392"))
implementation(project(":layer_3:module_3_288"))
implementation(project(":layer_3:module_3_359"))
implementation(project(":layer_3:module_3_351"))
implementation(project(":layer_3:module_3_264"))
implementation(project(":layer_3:module_3_329"))
implementation(project(":layer_3:module_3_280"))
implementation(project(":layer_3:module_3_303"))
implementation(project(":layer_3:module_3_356"))
implementation(project(":layer_3:module_3_283"))
implementation(project(":layer_3:module_3_370"))
implementation(project(":layer_3:module_3_402"))
implementation(project(":layer_3:module_3_342"))
implementation(project(":layer_3:module_3_339"))
implementation(project(":layer_3:module_3_297"))
implementation(project(":layer_3:module_3_345"))
implementation(project(":layer_3:module_3_393"))
implementation(project(":layer_3:module_3_272"))
implementation(project(":layer_3:module_3_321"))
implementation(project(":layer_3:module_3_263"))
implementation(project(":layer_3:module_3_286"))
          }
