       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_226"))
implementation(project(":layer_3:module_3_221"))
implementation(project(":layer_3:module_3_237"))
implementation(project(":layer_3:module_3_200"))
implementation(project(":layer_3:module_3_167"))
implementation(project(":layer_3:module_3_160"))
implementation(project(":layer_3:module_3_230"))
implementation(project(":layer_3:module_3_172"))
implementation(project(":layer_3:module_3_186"))
implementation(project(":layer_3:module_3_239"))
implementation(project(":layer_3:module_3_165"))
implementation(project(":layer_3:module_3_157"))
implementation(project(":layer_3:module_3_158"))
implementation(project(":layer_3:module_3_195"))
implementation(project(":layer_3:module_3_233"))
implementation(project(":layer_3:module_3_204"))
implementation(project(":layer_3:module_3_154"))
implementation(project(":layer_3:module_3_240"))
implementation(project(":layer_3:module_3_225"))
implementation(project(":layer_3:module_3_220"))
implementation(project(":layer_3:module_3_211"))
implementation(project(":layer_3:module_3_206"))
implementation(project(":layer_3:module_3_159"))
implementation(project(":layer_3:module_3_236"))
implementation(project(":layer_3:module_3_212"))
implementation(project(":layer_3:module_3_197"))
implementation(project(":layer_3:module_3_174"))
implementation(project(":layer_3:module_3_189"))
implementation(project(":layer_3:module_3_166"))
implementation(project(":layer_3:module_3_177"))
implementation(project(":layer_3:module_3_234"))
implementation(project(":layer_3:module_3_207"))
implementation(project(":layer_3:module_3_215"))
implementation(project(":layer_3:module_3_214"))
implementation(project(":layer_3:module_3_199"))
implementation(project(":layer_3:module_3_190"))
implementation(project(":layer_3:module_3_169"))
implementation(project(":layer_3:module_3_163"))
implementation(project(":layer_3:module_3_184"))
implementation(project(":layer_3:module_3_192"))
implementation(project(":layer_3:module_3_231"))
implementation(project(":layer_3:module_3_205"))
implementation(project(":layer_3:module_3_180"))
implementation(project(":layer_3:module_3_203"))
implementation(project(":layer_3:module_3_213"))
implementation(project(":layer_3:module_3_194"))
implementation(project(":layer_3:module_3_161"))
implementation(project(":layer_3:module_3_168"))
implementation(project(":layer_3:module_3_241"))
implementation(project(":layer_3:module_3_198"))
implementation(project(":layer_3:module_3_182"))
          }
