       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_157"))
implementation(project(":layer_3:module_3_241"))
implementation(project(":layer_3:module_3_191"))
implementation(project(":layer_3:module_3_177"))
implementation(project(":layer_3:module_3_169"))
implementation(project(":layer_3:module_3_227"))
implementation(project(":layer_3:module_3_163"))
implementation(project(":layer_3:module_3_222"))
implementation(project(":layer_3:module_3_197"))
implementation(project(":layer_3:module_3_198"))
implementation(project(":layer_3:module_3_202"))
implementation(project(":layer_3:module_3_161"))
implementation(project(":layer_3:module_3_192"))
implementation(project(":layer_3:module_3_166"))
implementation(project(":layer_3:module_3_206"))
implementation(project(":layer_3:module_3_199"))
implementation(project(":layer_3:module_3_204"))
implementation(project(":layer_3:module_3_193"))
implementation(project(":layer_3:module_3_240"))
implementation(project(":layer_3:module_3_158"))
implementation(project(":layer_3:module_3_154"))
implementation(project(":layer_3:module_3_156"))
implementation(project(":layer_3:module_3_165"))
implementation(project(":layer_3:module_3_230"))
implementation(project(":layer_3:module_3_226"))
implementation(project(":layer_3:module_3_183"))
implementation(project(":layer_3:module_3_186"))
implementation(project(":layer_3:module_3_201"))
implementation(project(":layer_3:module_3_195"))
implementation(project(":layer_3:module_3_228"))
implementation(project(":layer_3:module_3_229"))
implementation(project(":layer_3:module_3_188"))
implementation(project(":layer_3:module_3_159"))
implementation(project(":layer_3:module_3_218"))
          }
