       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_178"))
implementation(project(":layer_3:module_3_169"))
implementation(project(":layer_3:module_3_176"))
implementation(project(":layer_3:module_3_236"))
implementation(project(":layer_3:module_3_172"))
implementation(project(":layer_3:module_3_173"))
implementation(project(":layer_3:module_3_188"))
implementation(project(":layer_3:module_3_154"))
implementation(project(":layer_3:module_3_192"))
implementation(project(":layer_3:module_3_235"))
implementation(project(":layer_3:module_3_223"))
implementation(project(":layer_3:module_3_232"))
implementation(project(":layer_3:module_3_202"))
implementation(project(":layer_3:module_3_221"))
implementation(project(":layer_3:module_3_193"))
implementation(project(":layer_3:module_3_210"))
implementation(project(":layer_3:module_3_230"))
implementation(project(":layer_3:module_3_228"))
implementation(project(":layer_3:module_3_234"))
implementation(project(":layer_3:module_3_226"))
implementation(project(":layer_3:module_3_215"))
implementation(project(":layer_3:module_3_157"))
implementation(project(":layer_3:module_3_179"))
implementation(project(":layer_3:module_3_181"))
implementation(project(":layer_3:module_3_156"))
implementation(project(":layer_3:module_3_212"))
implementation(project(":layer_3:module_3_207"))
implementation(project(":layer_3:module_3_205"))
implementation(project(":layer_3:module_3_231"))
implementation(project(":layer_3:module_3_162"))
implementation(project(":layer_3:module_3_238"))
implementation(project(":layer_3:module_3_216"))
implementation(project(":layer_3:module_3_209"))
implementation(project(":layer_3:module_3_170"))
implementation(project(":layer_3:module_3_225"))
          }
