       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_304"))
implementation(project(":layer_3:module_3_289"))
implementation(project(":layer_3:module_3_303"))
implementation(project(":layer_3:module_3_368"))
implementation(project(":layer_3:module_3_377"))
implementation(project(":layer_3:module_3_278"))
implementation(project(":layer_3:module_3_260"))
implementation(project(":layer_3:module_3_375"))
implementation(project(":layer_3:module_3_325"))
implementation(project(":layer_3:module_3_391"))
implementation(project(":layer_3:module_3_274"))
implementation(project(":layer_3:module_3_282"))
implementation(project(":layer_3:module_3_283"))
implementation(project(":layer_3:module_3_280"))
implementation(project(":layer_3:module_3_266"))
implementation(project(":layer_3:module_3_355"))
implementation(project(":layer_3:module_3_306"))
implementation(project(":layer_3:module_3_333"))
implementation(project(":layer_3:module_3_323"))
implementation(project(":layer_3:module_3_386"))
implementation(project(":layer_3:module_3_357"))
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_277"))
implementation(project(":layer_3:module_3_367"))
implementation(project(":layer_3:module_3_366"))
implementation(project(":layer_3:module_3_310"))
implementation(project(":layer_3:module_3_326"))
implementation(project(":layer_3:module_3_336"))
implementation(project(":layer_3:module_3_345"))
implementation(project(":layer_3:module_3_314"))
implementation(project(":layer_3:module_3_309"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_316"))
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_294"))
implementation(project(":layer_3:module_3_296"))
implementation(project(":layer_3:module_3_273"))
implementation(project(":layer_3:module_3_344"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_382"))
implementation(project(":layer_3:module_3_376"))
implementation(project(":layer_3:module_3_256"))
          }
