       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_313"))
implementation(project(":layer_3:module_3_310"))
implementation(project(":layer_3:module_3_312"))
implementation(project(":layer_3:module_3_404"))
implementation(project(":layer_3:module_3_326"))
implementation(project(":layer_3:module_3_367"))
implementation(project(":layer_3:module_3_261"))
implementation(project(":layer_3:module_3_271"))
implementation(project(":layer_3:module_3_322"))
implementation(project(":layer_3:module_3_269"))
implementation(project(":layer_3:module_3_335"))
implementation(project(":layer_3:module_3_263"))
implementation(project(":layer_3:module_3_296"))
implementation(project(":layer_3:module_3_396"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_374"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_372"))
implementation(project(":layer_3:module_3_257"))
implementation(project(":layer_3:module_3_319"))
implementation(project(":layer_3:module_3_284"))
implementation(project(":layer_3:module_3_354"))
implementation(project(":layer_3:module_3_347"))
implementation(project(":layer_3:module_3_362"))
implementation(project(":layer_3:module_3_256"))
implementation(project(":layer_3:module_3_350"))
implementation(project(":layer_3:module_3_343"))
implementation(project(":layer_3:module_3_302"))
implementation(project(":layer_3:module_3_286"))
implementation(project(":layer_3:module_3_267"))
implementation(project(":layer_3:module_3_344"))
implementation(project(":layer_3:module_3_333"))
implementation(project(":layer_3:module_3_315"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_265"))
implementation(project(":layer_3:module_3_303"))
implementation(project(":layer_3:module_3_394"))
implementation(project(":layer_3:module_3_274"))
implementation(project(":layer_3:module_3_323"))
implementation(project(":layer_3:module_3_368"))
implementation(project(":layer_3:module_3_264"))
implementation(project(":layer_3:module_3_278"))
implementation(project(":layer_3:module_3_402"))
implementation(project(":layer_3:module_3_300"))
implementation(project(":layer_3:module_3_320"))
implementation(project(":layer_3:module_3_260"))
implementation(project(":layer_3:module_3_317"))
implementation(project(":layer_3:module_3_375"))
implementation(project(":layer_3:module_3_330"))
implementation(project(":layer_3:module_3_390"))
          }
