       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_329"))
implementation(project(":layer_3:module_3_366"))
implementation(project(":layer_3:module_3_342"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_291"))
implementation(project(":layer_3:module_3_353"))
implementation(project(":layer_3:module_3_358"))
implementation(project(":layer_3:module_3_386"))
implementation(project(":layer_3:module_3_356"))
implementation(project(":layer_3:module_3_279"))
implementation(project(":layer_3:module_3_273"))
implementation(project(":layer_3:module_3_282"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_292"))
implementation(project(":layer_3:module_3_269"))
implementation(project(":layer_3:module_3_403"))
implementation(project(":layer_3:module_3_337"))
implementation(project(":layer_3:module_3_372"))
implementation(project(":layer_3:module_3_266"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_395"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_390"))
implementation(project(":layer_3:module_3_294"))
implementation(project(":layer_3:module_3_260"))
implementation(project(":layer_3:module_3_335"))
implementation(project(":layer_3:module_3_402"))
implementation(project(":layer_3:module_3_299"))
implementation(project(":layer_3:module_3_346"))
implementation(project(":layer_3:module_3_268"))
implementation(project(":layer_3:module_3_257"))
implementation(project(":layer_3:module_3_368"))
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_313"))
implementation(project(":layer_3:module_3_267"))
implementation(project(":layer_3:module_3_351"))
implementation(project(":layer_3:module_3_347"))
implementation(project(":layer_3:module_3_320"))
implementation(project(":layer_3:module_3_378"))
implementation(project(":layer_3:module_3_363"))
implementation(project(":layer_3:module_3_382"))
implementation(project(":layer_3:module_3_310"))
implementation(project(":layer_3:module_3_349"))
implementation(project(":layer_3:module_3_264"))
implementation(project(":layer_3:module_3_404"))
          }
