       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_324"))
implementation(project(":layer_3:module_3_273"))
implementation(project(":layer_3:module_3_376"))
implementation(project(":layer_3:module_3_352"))
implementation(project(":layer_3:module_3_275"))
implementation(project(":layer_3:module_3_298"))
implementation(project(":layer_3:module_3_317"))
implementation(project(":layer_3:module_3_312"))
implementation(project(":layer_3:module_3_353"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_262"))
implementation(project(":layer_3:module_3_367"))
implementation(project(":layer_3:module_3_390"))
implementation(project(":layer_3:module_3_384"))
implementation(project(":layer_3:module_3_285"))
implementation(project(":layer_3:module_3_346"))
implementation(project(":layer_3:module_3_398"))
implementation(project(":layer_3:module_3_389"))
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_258"))
implementation(project(":layer_3:module_3_311"))
implementation(project(":layer_3:module_3_328"))
implementation(project(":layer_3:module_3_284"))
implementation(project(":layer_3:module_3_380"))
implementation(project(":layer_3:module_3_391"))
implementation(project(":layer_3:module_3_257"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_269"))
implementation(project(":layer_3:module_3_332"))
implementation(project(":layer_3:module_3_355"))
implementation(project(":layer_3:module_3_297"))
implementation(project(":layer_3:module_3_378"))
implementation(project(":layer_3:module_3_293"))
implementation(project(":layer_3:module_3_382"))
implementation(project(":layer_3:module_3_403"))
implementation(project(":layer_3:module_3_368"))
implementation(project(":layer_3:module_3_261"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_309"))
implementation(project(":layer_3:module_3_364"))
implementation(project(":layer_3:module_3_330"))
implementation(project(":layer_3:module_3_308"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_357"))
implementation(project(":layer_3:module_3_338"))
implementation(project(":layer_3:module_3_274"))
implementation(project(":layer_3:module_3_290"))
implementation(project(":layer_3:module_3_315"))
implementation(project(":layer_3:module_3_375"))
implementation(project(":layer_3:module_3_319"))
implementation(project(":layer_3:module_3_321"))
implementation(project(":layer_3:module_3_287"))
implementation(project(":layer_3:module_3_331"))
implementation(project(":layer_3:module_3_350"))
implementation(project(":layer_3:module_3_349"))
implementation(project(":layer_3:module_3_362"))
implementation(project(":layer_3:module_3_323"))
implementation(project(":layer_3:module_3_334"))
          }
