       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_193"))
implementation(project(":layer_3:module_3_198"))
implementation(project(":layer_3:module_3_209"))
implementation(project(":layer_3:module_3_237"))
implementation(project(":layer_3:module_3_175"))
implementation(project(":layer_3:module_3_232"))
implementation(project(":layer_3:module_3_163"))
implementation(project(":layer_3:module_3_205"))
implementation(project(":layer_3:module_3_183"))
implementation(project(":layer_3:module_3_243"))
implementation(project(":layer_3:module_3_171"))
implementation(project(":layer_3:module_3_176"))
implementation(project(":layer_3:module_3_161"))
implementation(project(":layer_3:module_3_223"))
implementation(project(":layer_3:module_3_178"))
implementation(project(":layer_3:module_3_233"))
implementation(project(":layer_3:module_3_236"))
implementation(project(":layer_3:module_3_192"))
implementation(project(":layer_3:module_3_206"))
implementation(project(":layer_3:module_3_167"))
implementation(project(":layer_3:module_3_207"))
implementation(project(":layer_3:module_3_226"))
implementation(project(":layer_3:module_3_213"))
implementation(project(":layer_3:module_3_180"))
implementation(project(":layer_3:module_3_194"))
implementation(project(":layer_3:module_3_172"))
implementation(project(":layer_3:module_3_200"))
implementation(project(":layer_3:module_3_184"))
          }
