       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_346"))
implementation(project(":layer_3:module_3_281"))
implementation(project(":layer_3:module_3_364"))
implementation(project(":layer_3:module_3_366"))
implementation(project(":layer_3:module_3_295"))
implementation(project(":layer_3:module_3_388"))
implementation(project(":layer_3:module_3_385"))
implementation(project(":layer_3:module_3_351"))
implementation(project(":layer_3:module_3_317"))
implementation(project(":layer_3:module_3_287"))
implementation(project(":layer_3:module_3_270"))
implementation(project(":layer_3:module_3_345"))
implementation(project(":layer_3:module_3_273"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_396"))
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_333"))
implementation(project(":layer_3:module_3_257"))
implementation(project(":layer_3:module_3_324"))
implementation(project(":layer_3:module_3_378"))
implementation(project(":layer_3:module_3_310"))
implementation(project(":layer_3:module_3_375"))
implementation(project(":layer_3:module_3_395"))
implementation(project(":layer_3:module_3_327"))
implementation(project(":layer_3:module_3_262"))
implementation(project(":layer_3:module_3_341"))
implementation(project(":layer_3:module_3_283"))
implementation(project(":layer_3:module_3_296"))
implementation(project(":layer_3:module_3_267"))
implementation(project(":layer_3:module_3_367"))
implementation(project(":layer_3:module_3_373"))
implementation(project(":layer_3:module_3_394"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_361"))
implementation(project(":layer_3:module_3_405"))
implementation(project(":layer_3:module_3_282"))
implementation(project(":layer_3:module_3_278"))
implementation(project(":layer_3:module_3_280"))
implementation(project(":layer_3:module_3_308"))
implementation(project(":layer_3:module_3_337"))
implementation(project(":layer_3:module_3_386"))
implementation(project(":layer_3:module_3_381"))
implementation(project(":layer_3:module_3_389"))
implementation(project(":layer_3:module_3_363"))
implementation(project(":layer_3:module_3_353"))
implementation(project(":layer_3:module_3_329"))
implementation(project(":layer_3:module_3_319"))
implementation(project(":layer_3:module_3_304"))
implementation(project(":layer_3:module_3_349"))
implementation(project(":layer_3:module_3_379"))
implementation(project(":layer_3:module_3_260"))
implementation(project(":layer_3:module_3_347"))
implementation(project(":layer_3:module_3_332"))
implementation(project(":layer_3:module_3_350"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_265"))
implementation(project(":layer_3:module_3_344"))
implementation(project(":layer_3:module_3_403"))
implementation(project(":layer_3:module_3_368"))
implementation(project(":layer_3:module_3_397"))
implementation(project(":layer_3:module_3_284"))
implementation(project(":layer_3:module_3_269"))
          }
