       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_1:module_1_229"))
implementation(project(":layer_1:module_1_171"))
implementation(project(":layer_1:module_1_147"))
implementation(project(":layer_1:module_1_103"))
implementation(project(":layer_1:module_1_107"))
implementation(project(":layer_1:module_1_242"))
implementation(project(":layer_1:module_1_99"))
implementation(project(":layer_1:module_1_207"))
implementation(project(":layer_1:module_1_224"))
implementation(project(":layer_1:module_1_102"))
implementation(project(":layer_1:module_1_122"))
implementation(project(":layer_1:module_1_187"))
implementation(project(":layer_1:module_1_189"))
implementation(project(":layer_1:module_1_161"))
implementation(project(":layer_1:module_1_97"))
implementation(project(":layer_1:module_1_213"))
implementation(project(":layer_1:module_1_209"))
implementation(project(":layer_1:module_1_112"))
implementation(project(":layer_1:module_1_130"))
implementation(project(":layer_1:module_1_154"))
implementation(project(":layer_1:module_1_222"))
implementation(project(":layer_1:module_1_184"))
implementation(project(":layer_1:module_1_164"))
implementation(project(":layer_1:module_1_149"))
implementation(project(":layer_1:module_1_146"))
implementation(project(":layer_1:module_1_163"))
implementation(project(":layer_1:module_1_238"))
implementation(project(":layer_1:module_1_196"))
implementation(project(":layer_1:module_1_190"))
implementation(project(":layer_1:module_1_217"))
implementation(project(":layer_1:module_1_132"))
implementation(project(":layer_1:module_1_142"))
implementation(project(":layer_1:module_1_203"))
implementation(project(":layer_1:module_1_114"))
implementation(project(":layer_1:module_1_220"))
implementation(project(":layer_1:module_1_178"))
implementation(project(":layer_1:module_1_186"))
implementation(project(":layer_1:module_1_236"))
implementation(project(":layer_1:module_1_117"))
implementation(project(":layer_1:module_1_109"))
implementation(project(":layer_1:module_1_215"))
implementation(project(":layer_1:module_1_135"))
implementation(project(":layer_1:module_1_137"))
implementation(project(":layer_1:module_1_240"))
implementation(project(":layer_1:module_1_191"))
implementation(project(":layer_1:module_1_235"))
implementation(project(":layer_1:module_1_167"))
implementation(project(":layer_1:module_1_150"))
implementation(project(":layer_1:module_1_125"))
implementation(project(":layer_1:module_1_239"))
implementation(project(":layer_1:module_1_223"))
implementation(project(":layer_1:module_1_177"))
implementation(project(":layer_1:module_1_108"))
implementation(project(":layer_1:module_1_176"))
implementation(project(":layer_1:module_1_105"))
implementation(project(":layer_1:module_1_199"))
implementation(project(":layer_1:module_1_118"))
implementation(project(":layer_1:module_1_230"))
implementation(project(":layer_1:module_1_195"))
implementation(project(":layer_1:module_1_110"))
implementation(project(":layer_1:module_1_134"))
implementation(project(":layer_1:module_1_141"))
implementation(project(":layer_1:module_1_140"))
          }
