       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_21"))
implementation(project(":layer_0:module_0_8"))
implementation(project(":layer_0:module_0_46"))
implementation(project(":layer_0:module_0_48"))
implementation(project(":layer_0:module_0_50"))
implementation(project(":layer_0:module_0_10"))
implementation(project(":layer_0:module_0_5"))
implementation(project(":layer_0:module_0_37"))
implementation(project(":layer_0:module_0_29"))
implementation(project(":layer_0:module_0_47"))
implementation(project(":layer_0:module_0_32"))
implementation(project(":layer_0:module_0_36"))
implementation(project(":layer_0:module_0_11"))
implementation(project(":layer_0:module_0_3"))
implementation(project(":layer_0:module_0_45"))
implementation(project(":layer_0:module_0_54"))
implementation(project(":layer_0:module_0_41"))
implementation(project(":layer_0:module_0_35"))
implementation(project(":layer_0:module_0_14"))
implementation(project(":layer_0:module_0_28"))
implementation(project(":layer_0:module_0_56"))
implementation(project(":layer_0:module_0_42"))
implementation(project(":layer_0:module_0_52"))
implementation(project(":layer_0:module_0_57"))
implementation(project(":layer_0:module_0_31"))
implementation(project(":layer_0:module_0_23"))
implementation(project(":layer_0:module_0_27"))
implementation(project(":layer_0:module_0_12"))
implementation(project(":layer_0:module_0_26"))
implementation(project(":layer_0:module_0_20"))
implementation(project(":layer_0:module_0_34"))
implementation(project(":layer_0:module_0_40"))
implementation(project(":layer_0:module_0_13"))
implementation(project(":layer_0:module_0_39"))
implementation(project(":layer_0:module_0_49"))
implementation(project(":layer_0:module_0_22"))
          }
