       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_328"))
implementation(project(":layer_3:module_3_381"))
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_270"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_309"))
implementation(project(":layer_3:module_3_261"))
implementation(project(":layer_3:module_3_336"))
implementation(project(":layer_3:module_3_314"))
implementation(project(":layer_3:module_3_377"))
implementation(project(":layer_3:module_3_277"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_364"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_399"))
implementation(project(":layer_3:module_3_384"))
implementation(project(":layer_3:module_3_324"))
implementation(project(":layer_3:module_3_372"))
implementation(project(":layer_3:module_3_385"))
implementation(project(":layer_3:module_3_387"))
implementation(project(":layer_3:module_3_378"))
implementation(project(":layer_3:module_3_389"))
implementation(project(":layer_3:module_3_358"))
implementation(project(":layer_3:module_3_397"))
implementation(project(":layer_3:module_3_299"))
implementation(project(":layer_3:module_3_346"))
implementation(project(":layer_3:module_3_264"))
implementation(project(":layer_3:module_3_268"))
implementation(project(":layer_3:module_3_391"))
implementation(project(":layer_3:module_3_401"))
implementation(project(":layer_3:module_3_288"))
implementation(project(":layer_3:module_3_278"))
implementation(project(":layer_3:module_3_376"))
implementation(project(":layer_3:module_3_263"))
implementation(project(":layer_3:module_3_316"))
implementation(project(":layer_3:module_3_332"))
implementation(project(":layer_3:module_3_330"))
implementation(project(":layer_3:module_3_313"))
implementation(project(":layer_3:module_3_265"))
          }
