       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_24"))
implementation(project(":layer_0:module_0_10"))
implementation(project(":layer_0:module_0_88"))
implementation(project(":layer_0:module_0_66"))
implementation(project(":layer_0:module_0_44"))
implementation(project(":layer_0:module_0_43"))
implementation(project(":layer_0:module_0_68"))
implementation(project(":layer_0:module_0_79"))
implementation(project(":layer_0:module_0_53"))
implementation(project(":layer_0:module_0_61"))
implementation(project(":layer_0:module_0_16"))
implementation(project(":layer_0:module_0_18"))
implementation(project(":layer_0:module_0_70"))
implementation(project(":layer_0:module_0_4"))
implementation(project(":layer_0:module_0_72"))
implementation(project(":layer_0:module_0_54"))
implementation(project(":layer_0:module_0_52"))
implementation(project(":layer_0:module_0_95"))
implementation(project(":layer_0:module_0_58"))
implementation(project(":layer_0:module_0_48"))
implementation(project(":layer_0:module_0_5"))
implementation(project(":layer_0:module_0_26"))
implementation(project(":layer_0:module_0_77"))
implementation(project(":layer_0:module_0_14"))
implementation(project(":layer_0:module_0_15"))
implementation(project(":layer_0:module_0_45"))
implementation(project(":layer_0:module_0_84"))
implementation(project(":layer_0:module_0_38"))
          }
