       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_24"))
implementation(project(":layer_0:module_0_26"))
implementation(project(":layer_0:module_0_19"))
implementation(project(":layer_0:module_0_50"))
implementation(project(":layer_0:module_0_2"))
implementation(project(":layer_0:module_0_42"))
implementation(project(":layer_0:module_0_13"))
implementation(project(":layer_0:module_0_4"))
implementation(project(":layer_0:module_0_37"))
implementation(project(":layer_0:module_0_52"))
implementation(project(":layer_0:module_0_57"))
implementation(project(":layer_0:module_0_49"))
implementation(project(":layer_0:module_0_54"))
implementation(project(":layer_0:module_0_21"))
implementation(project(":layer_0:module_0_40"))
implementation(project(":layer_0:module_0_41"))
implementation(project(":layer_0:module_0_6"))
implementation(project(":layer_0:module_0_36"))
implementation(project(":layer_0:module_0_20"))
implementation(project(":layer_0:module_0_48"))
implementation(project(":layer_0:module_0_8"))
implementation(project(":layer_0:module_0_22"))
implementation(project(":layer_0:module_0_47"))
implementation(project(":layer_0:module_0_38"))
implementation(project(":layer_0:module_0_1"))
          }
