       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_294"))
implementation(project(":layer_3:module_3_363"))
implementation(project(":layer_3:module_3_349"))
implementation(project(":layer_3:module_3_313"))
implementation(project(":layer_3:module_3_374"))
implementation(project(":layer_3:module_3_390"))
implementation(project(":layer_3:module_3_341"))
implementation(project(":layer_3:module_3_267"))
implementation(project(":layer_3:module_3_380"))
implementation(project(":layer_3:module_3_330"))
implementation(project(":layer_3:module_3_326"))
implementation(project(":layer_3:module_3_328"))
implementation(project(":layer_3:module_3_279"))
implementation(project(":layer_3:module_3_334"))
implementation(project(":layer_3:module_3_347"))
implementation(project(":layer_3:module_3_343"))
implementation(project(":layer_3:module_3_310"))
implementation(project(":layer_3:module_3_333"))
implementation(project(":layer_3:module_3_327"))
implementation(project(":layer_3:module_3_364"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_377"))
implementation(project(":layer_3:module_3_306"))
implementation(project(":layer_3:module_3_296"))
implementation(project(":layer_3:module_3_321"))
implementation(project(":layer_3:module_3_300"))
implementation(project(":layer_3:module_3_260"))
implementation(project(":layer_3:module_3_323"))
implementation(project(":layer_3:module_3_281"))
implementation(project(":layer_3:module_3_354"))
implementation(project(":layer_3:module_3_316"))
implementation(project(":layer_3:module_3_397"))
implementation(project(":layer_3:module_3_299"))
implementation(project(":layer_3:module_3_384"))
implementation(project(":layer_3:module_3_404"))
implementation(project(":layer_3:module_3_322"))
implementation(project(":layer_3:module_3_398"))
implementation(project(":layer_3:module_3_295"))
implementation(project(":layer_3:module_3_350"))
implementation(project(":layer_3:module_3_272"))
implementation(project(":layer_3:module_3_342"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_325"))
          }
