       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_1:module_1_237"))
implementation(project(":layer_1:module_1_112"))
implementation(project(":layer_1:module_1_241"))
implementation(project(":layer_1:module_1_152"))
implementation(project(":layer_1:module_1_245"))
implementation(project(":layer_1:module_1_130"))
implementation(project(":layer_1:module_1_103"))
implementation(project(":layer_1:module_1_207"))
implementation(project(":layer_1:module_1_169"))
implementation(project(":layer_1:module_1_233"))
implementation(project(":layer_1:module_1_202"))
implementation(project(":layer_1:module_1_201"))
implementation(project(":layer_1:module_1_194"))
implementation(project(":layer_1:module_1_171"))
implementation(project(":layer_1:module_1_127"))
implementation(project(":layer_1:module_1_190"))
implementation(project(":layer_1:module_1_228"))
implementation(project(":layer_1:module_1_114"))
implementation(project(":layer_1:module_1_180"))
implementation(project(":layer_1:module_1_129"))
implementation(project(":layer_1:module_1_167"))
implementation(project(":layer_1:module_1_238"))
implementation(project(":layer_1:module_1_157"))
implementation(project(":layer_1:module_1_210"))
implementation(project(":layer_1:module_1_139"))
implementation(project(":layer_1:module_1_183"))
implementation(project(":layer_1:module_1_217"))
implementation(project(":layer_1:module_1_206"))
implementation(project(":layer_1:module_1_118"))
implementation(project(":layer_1:module_1_117"))
implementation(project(":layer_1:module_1_231"))
implementation(project(":layer_1:module_1_186"))
implementation(project(":layer_1:module_1_223"))
implementation(project(":layer_1:module_1_132"))
implementation(project(":layer_1:module_1_97"))
implementation(project(":layer_1:module_1_110"))
implementation(project(":layer_1:module_1_195"))
implementation(project(":layer_1:module_1_135"))
implementation(project(":layer_1:module_1_219"))
implementation(project(":layer_1:module_1_209"))
implementation(project(":layer_1:module_1_184"))
implementation(project(":layer_1:module_1_161"))
implementation(project(":layer_1:module_1_208"))
implementation(project(":layer_1:module_1_244"))
implementation(project(":layer_1:module_1_133"))
implementation(project(":layer_1:module_1_143"))
implementation(project(":layer_1:module_1_211"))
implementation(project(":layer_1:module_1_155"))
implementation(project(":layer_1:module_1_146"))
implementation(project(":layer_1:module_1_107"))
implementation(project(":layer_1:module_1_120"))
implementation(project(":layer_1:module_1_99"))
implementation(project(":layer_1:module_1_175"))
implementation(project(":layer_1:module_1_165"))
implementation(project(":layer_1:module_1_234"))
implementation(project(":layer_1:module_1_111"))
          }
