       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_333"))
implementation(project(":layer_3:module_3_353"))
implementation(project(":layer_3:module_3_271"))
implementation(project(":layer_3:module_3_281"))
implementation(project(":layer_3:module_3_290"))
implementation(project(":layer_3:module_3_351"))
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_342"))
implementation(project(":layer_3:module_3_317"))
implementation(project(":layer_3:module_3_295"))
implementation(project(":layer_3:module_3_292"))
implementation(project(":layer_3:module_3_296"))
implementation(project(":layer_3:module_3_294"))
implementation(project(":layer_3:module_3_395"))
implementation(project(":layer_3:module_3_313"))
implementation(project(":layer_3:module_3_389"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_373"))
implementation(project(":layer_3:module_3_398"))
implementation(project(":layer_3:module_3_384"))
implementation(project(":layer_3:module_3_321"))
implementation(project(":layer_3:module_3_319"))
implementation(project(":layer_3:module_3_393"))
implementation(project(":layer_3:module_3_303"))
implementation(project(":layer_3:module_3_339"))
implementation(project(":layer_3:module_3_315"))
implementation(project(":layer_3:module_3_388"))
implementation(project(":layer_3:module_3_344"))
implementation(project(":layer_3:module_3_261"))
implementation(project(":layer_3:module_3_336"))
implementation(project(":layer_3:module_3_262"))
implementation(project(":layer_3:module_3_314"))
implementation(project(":layer_3:module_3_341"))
implementation(project(":layer_3:module_3_360"))
implementation(project(":layer_3:module_3_355"))
implementation(project(":layer_3:module_3_264"))
implementation(project(":layer_3:module_3_288"))
implementation(project(":layer_3:module_3_278"))
implementation(project(":layer_3:module_3_375"))
implementation(project(":layer_3:module_3_277"))
implementation(project(":layer_3:module_3_334"))
implementation(project(":layer_3:module_3_349"))
implementation(project(":layer_3:module_3_331"))
          }
