       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_356"))
implementation(project(":layer_3:module_3_336"))
implementation(project(":layer_3:module_3_314"))
implementation(project(":layer_3:module_3_274"))
implementation(project(":layer_3:module_3_256"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_352"))
implementation(project(":layer_3:module_3_310"))
implementation(project(":layer_3:module_3_359"))
implementation(project(":layer_3:module_3_364"))
implementation(project(":layer_3:module_3_350"))
implementation(project(":layer_3:module_3_297"))
implementation(project(":layer_3:module_3_272"))
implementation(project(":layer_3:module_3_268"))
implementation(project(":layer_3:module_3_358"))
implementation(project(":layer_3:module_3_393"))
implementation(project(":layer_3:module_3_257"))
implementation(project(":layer_3:module_3_337"))
implementation(project(":layer_3:module_3_295"))
implementation(project(":layer_3:module_3_389"))
implementation(project(":layer_3:module_3_288"))
implementation(project(":layer_3:module_3_373"))
implementation(project(":layer_3:module_3_282"))
implementation(project(":layer_3:module_3_290"))
implementation(project(":layer_3:module_3_308"))
implementation(project(":layer_3:module_3_351"))
implementation(project(":layer_3:module_3_296"))
implementation(project(":layer_3:module_3_381"))
implementation(project(":layer_3:module_3_401"))
implementation(project(":layer_3:module_3_280"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_324"))
implementation(project(":layer_3:module_3_306"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_266"))
implementation(project(":layer_3:module_3_271"))
implementation(project(":layer_3:module_3_398"))
implementation(project(":layer_3:module_3_332"))
implementation(project(":layer_3:module_3_264"))
implementation(project(":layer_3:module_3_286"))
          }
