       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_27"))
implementation(project(":layer_0:module_0_33"))
implementation(project(":layer_0:module_0_34"))
implementation(project(":layer_0:module_0_17"))
implementation(project(":layer_0:module_0_45"))
implementation(project(":layer_0:module_0_58"))
implementation(project(":layer_0:module_0_3"))
implementation(project(":layer_0:module_0_53"))
implementation(project(":layer_0:module_0_6"))
implementation(project(":layer_0:module_0_8"))
implementation(project(":layer_0:module_0_65"))
implementation(project(":layer_0:module_0_80"))
implementation(project(":layer_0:module_0_84"))
implementation(project(":layer_0:module_0_26"))
implementation(project(":layer_0:module_0_78"))
implementation(project(":layer_0:module_0_47"))
implementation(project(":layer_0:module_0_54"))
implementation(project(":layer_0:module_0_57"))
implementation(project(":layer_0:module_0_55"))
implementation(project(":layer_0:module_0_56"))
implementation(project(":layer_0:module_0_36"))
implementation(project(":layer_0:module_0_9"))
implementation(project(":layer_0:module_0_46"))
implementation(project(":layer_0:module_0_23"))
implementation(project(":layer_0:module_0_22"))
implementation(project(":layer_0:module_0_83"))
implementation(project(":layer_0:module_0_75"))
implementation(project(":layer_0:module_0_20"))
          }
