       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_8"))
implementation(project(":layer_0:module_0_44"))
implementation(project(":layer_0:module_0_52"))
implementation(project(":layer_0:module_0_29"))
implementation(project(":layer_0:module_0_31"))
implementation(project(":layer_0:module_0_22"))
implementation(project(":layer_0:module_0_35"))
implementation(project(":layer_0:module_0_30"))
implementation(project(":layer_0:module_0_48"))
implementation(project(":layer_0:module_0_18"))
implementation(project(":layer_0:module_0_23"))
implementation(project(":layer_0:module_0_6"))
implementation(project(":layer_0:module_0_43"))
implementation(project(":layer_0:module_0_36"))
implementation(project(":layer_0:module_0_27"))
implementation(project(":layer_0:module_0_54"))
implementation(project(":layer_0:module_0_26"))
implementation(project(":layer_0:module_0_37"))
implementation(project(":layer_0:module_0_50"))
implementation(project(":layer_0:module_0_49"))
implementation(project(":layer_0:module_0_2"))
implementation(project(":layer_0:module_0_17"))
implementation(project(":layer_0:module_0_12"))
implementation(project(":layer_0:module_0_19"))
implementation(project(":layer_0:module_0_38"))
          }
