       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_390"))
implementation(project(":layer_3:module_3_321"))
implementation(project(":layer_3:module_3_373"))
implementation(project(":layer_3:module_3_361"))
implementation(project(":layer_3:module_3_262"))
implementation(project(":layer_3:module_3_331"))
implementation(project(":layer_3:module_3_309"))
implementation(project(":layer_3:module_3_269"))
implementation(project(":layer_3:module_3_300"))
implementation(project(":layer_3:module_3_282"))
implementation(project(":layer_3:module_3_398"))
implementation(project(":layer_3:module_3_405"))
implementation(project(":layer_3:module_3_357"))
implementation(project(":layer_3:module_3_292"))
implementation(project(":layer_3:module_3_291"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_403"))
implementation(project(":layer_3:module_3_272"))
implementation(project(":layer_3:module_3_388"))
implementation(project(":layer_3:module_3_393"))
implementation(project(":layer_3:module_3_395"))
implementation(project(":layer_3:module_3_256"))
implementation(project(":layer_3:module_3_377"))
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_402"))
implementation(project(":layer_3:module_3_389"))
implementation(project(":layer_3:module_3_326"))
implementation(project(":layer_3:module_3_350"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_345"))
implementation(project(":layer_3:module_3_325"))
implementation(project(":layer_3:module_3_330"))
implementation(project(":layer_3:module_3_313"))
implementation(project(":layer_3:module_3_343"))
implementation(project(":layer_3:module_3_387"))
implementation(project(":layer_3:module_3_337"))
implementation(project(":layer_3:module_3_284"))
implementation(project(":layer_3:module_3_293"))
implementation(project(":layer_3:module_3_360"))
implementation(project(":layer_3:module_3_304"))
implementation(project(":layer_3:module_3_354"))
implementation(project(":layer_3:module_3_362"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_404"))
implementation(project(":layer_3:module_3_260"))
implementation(project(":layer_3:module_3_257"))
implementation(project(":layer_3:module_3_344"))
implementation(project(":layer_3:module_3_332"))
implementation(project(":layer_3:module_3_303"))
implementation(project(":layer_3:module_3_274"))
          }
