       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_180"))
implementation(project(":layer_3:module_3_227"))
implementation(project(":layer_3:module_3_176"))
implementation(project(":layer_3:module_3_184"))
implementation(project(":layer_3:module_3_235"))
implementation(project(":layer_3:module_3_211"))
implementation(project(":layer_3:module_3_207"))
implementation(project(":layer_3:module_3_210"))
implementation(project(":layer_3:module_3_187"))
implementation(project(":layer_3:module_3_197"))
implementation(project(":layer_3:module_3_243"))
implementation(project(":layer_3:module_3_206"))
implementation(project(":layer_3:module_3_169"))
implementation(project(":layer_3:module_3_171"))
implementation(project(":layer_3:module_3_159"))
implementation(project(":layer_3:module_3_232"))
implementation(project(":layer_3:module_3_193"))
implementation(project(":layer_3:module_3_185"))
implementation(project(":layer_3:module_3_158"))
implementation(project(":layer_3:module_3_154"))
implementation(project(":layer_3:module_3_162"))
implementation(project(":layer_3:module_3_230"))
implementation(project(":layer_3:module_3_204"))
implementation(project(":layer_3:module_3_191"))
implementation(project(":layer_3:module_3_155"))
implementation(project(":layer_3:module_3_242"))
implementation(project(":layer_3:module_3_236"))
          }
