       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_275"))
implementation(project(":layer_3:module_3_260"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_293"))
implementation(project(":layer_3:module_3_341"))
implementation(project(":layer_3:module_3_303"))
implementation(project(":layer_3:module_3_353"))
implementation(project(":layer_3:module_3_329"))
implementation(project(":layer_3:module_3_335"))
implementation(project(":layer_3:module_3_272"))
implementation(project(":layer_3:module_3_317"))
implementation(project(":layer_3:module_3_379"))
implementation(project(":layer_3:module_3_399"))
implementation(project(":layer_3:module_3_316"))
implementation(project(":layer_3:module_3_309"))
implementation(project(":layer_3:module_3_268"))
implementation(project(":layer_3:module_3_359"))
implementation(project(":layer_3:module_3_315"))
implementation(project(":layer_3:module_3_321"))
implementation(project(":layer_3:module_3_376"))
implementation(project(":layer_3:module_3_404"))
implementation(project(":layer_3:module_3_312"))
implementation(project(":layer_3:module_3_288"))
implementation(project(":layer_3:module_3_345"))
implementation(project(":layer_3:module_3_261"))
implementation(project(":layer_3:module_3_358"))
implementation(project(":layer_3:module_3_313"))
implementation(project(":layer_3:module_3_267"))
implementation(project(":layer_3:module_3_258"))
implementation(project(":layer_3:module_3_361"))
implementation(project(":layer_3:module_3_281"))
implementation(project(":layer_3:module_3_292"))
implementation(project(":layer_3:module_3_350"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_269"))
implementation(project(":layer_3:module_3_263"))
implementation(project(":layer_3:module_3_354"))
implementation(project(":layer_3:module_3_294"))
implementation(project(":layer_3:module_3_396"))
implementation(project(":layer_3:module_3_323"))
implementation(project(":layer_3:module_3_380"))
implementation(project(":layer_3:module_3_257"))
implementation(project(":layer_3:module_3_297"))
implementation(project(":layer_3:module_3_287"))
implementation(project(":layer_3:module_3_367"))
implementation(project(":layer_3:module_3_305"))
implementation(project(":layer_3:module_3_327"))
implementation(project(":layer_3:module_3_369"))
implementation(project(":layer_3:module_3_384"))
implementation(project(":layer_3:module_3_307"))
implementation(project(":layer_3:module_3_366"))
implementation(project(":layer_3:module_3_308"))
implementation(project(":layer_3:module_3_286"))
implementation(project(":layer_3:module_3_374"))
implementation(project(":layer_3:module_3_357"))
implementation(project(":layer_3:module_3_398"))
implementation(project(":layer_3:module_3_320"))
implementation(project(":layer_3:module_3_270"))
          }
