       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_298"))
implementation(project(":layer_3:module_3_292"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_274"))
implementation(project(":layer_3:module_3_343"))
implementation(project(":layer_3:module_3_372"))
implementation(project(":layer_3:module_3_384"))
implementation(project(":layer_3:module_3_361"))
implementation(project(":layer_3:module_3_360"))
implementation(project(":layer_3:module_3_314"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_379"))
implementation(project(":layer_3:module_3_345"))
implementation(project(":layer_3:module_3_278"))
implementation(project(":layer_3:module_3_266"))
implementation(project(":layer_3:module_3_309"))
implementation(project(":layer_3:module_3_396"))
implementation(project(":layer_3:module_3_300"))
implementation(project(":layer_3:module_3_357"))
implementation(project(":layer_3:module_3_289"))
implementation(project(":layer_3:module_3_271"))
implementation(project(":layer_3:module_3_331"))
implementation(project(":layer_3:module_3_393"))
implementation(project(":layer_3:module_3_355"))
implementation(project(":layer_3:module_3_385"))
implementation(project(":layer_3:module_3_392"))
implementation(project(":layer_3:module_3_284"))
implementation(project(":layer_3:module_3_335"))
implementation(project(":layer_3:module_3_364"))
implementation(project(":layer_3:module_3_391"))
implementation(project(":layer_3:module_3_339"))
          }
