       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_185"))
implementation(project(":layer_3:module_3_161"))
implementation(project(":layer_3:module_3_211"))
implementation(project(":layer_3:module_3_193"))
implementation(project(":layer_3:module_3_158"))
implementation(project(":layer_3:module_3_230"))
implementation(project(":layer_3:module_3_219"))
implementation(project(":layer_3:module_3_191"))
implementation(project(":layer_3:module_3_176"))
implementation(project(":layer_3:module_3_154"))
implementation(project(":layer_3:module_3_170"))
implementation(project(":layer_3:module_3_235"))
implementation(project(":layer_3:module_3_166"))
implementation(project(":layer_3:module_3_223"))
implementation(project(":layer_3:module_3_184"))
implementation(project(":layer_3:module_3_180"))
implementation(project(":layer_3:module_3_182"))
implementation(project(":layer_3:module_3_183"))
implementation(project(":layer_3:module_3_213"))
implementation(project(":layer_3:module_3_195"))
implementation(project(":layer_3:module_3_217"))
implementation(project(":layer_3:module_3_189"))
implementation(project(":layer_3:module_3_197"))
implementation(project(":layer_3:module_3_224"))
implementation(project(":layer_3:module_3_169"))
implementation(project(":layer_3:module_3_163"))
implementation(project(":layer_3:module_3_200"))
implementation(project(":layer_3:module_3_207"))
implementation(project(":layer_3:module_3_204"))
implementation(project(":layer_3:module_3_179"))
implementation(project(":layer_3:module_3_167"))
implementation(project(":layer_3:module_3_238"))
implementation(project(":layer_3:module_3_209"))
implementation(project(":layer_3:module_3_241"))
implementation(project(":layer_3:module_3_202"))
implementation(project(":layer_3:module_3_159"))
implementation(project(":layer_3:module_3_165"))
implementation(project(":layer_3:module_3_156"))
implementation(project(":layer_3:module_3_162"))
implementation(project(":layer_3:module_3_229"))
implementation(project(":layer_3:module_3_155"))
implementation(project(":layer_3:module_3_228"))
implementation(project(":layer_3:module_3_226"))
implementation(project(":layer_3:module_3_206"))
implementation(project(":layer_3:module_3_236"))
implementation(project(":layer_3:module_3_196"))
          }
