       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_274"))
implementation(project(":layer_3:module_3_281"))
implementation(project(":layer_3:module_3_375"))
implementation(project(":layer_3:module_3_376"))
implementation(project(":layer_3:module_3_277"))
implementation(project(":layer_3:module_3_357"))
implementation(project(":layer_3:module_3_313"))
implementation(project(":layer_3:module_3_262"))
implementation(project(":layer_3:module_3_343"))
implementation(project(":layer_3:module_3_275"))
implementation(project(":layer_3:module_3_293"))
implementation(project(":layer_3:module_3_388"))
implementation(project(":layer_3:module_3_362"))
implementation(project(":layer_3:module_3_322"))
implementation(project(":layer_3:module_3_331"))
implementation(project(":layer_3:module_3_337"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_401"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_286"))
implementation(project(":layer_3:module_3_370"))
implementation(project(":layer_3:module_3_391"))
implementation(project(":layer_3:module_3_326"))
implementation(project(":layer_3:module_3_305"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_271"))
          }
