       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_405"))
implementation(project(":layer_3:module_3_279"))
implementation(project(":layer_3:module_3_290"))
implementation(project(":layer_3:module_3_371"))
implementation(project(":layer_3:module_3_325"))
implementation(project(":layer_3:module_3_379"))
implementation(project(":layer_3:module_3_393"))
implementation(project(":layer_3:module_3_374"))
implementation(project(":layer_3:module_3_285"))
implementation(project(":layer_3:module_3_277"))
implementation(project(":layer_3:module_3_265"))
implementation(project(":layer_3:module_3_328"))
implementation(project(":layer_3:module_3_395"))
implementation(project(":layer_3:module_3_387"))
implementation(project(":layer_3:module_3_260"))
implementation(project(":layer_3:module_3_311"))
implementation(project(":layer_3:module_3_402"))
implementation(project(":layer_3:module_3_364"))
implementation(project(":layer_3:module_3_404"))
implementation(project(":layer_3:module_3_298"))
implementation(project(":layer_3:module_3_270"))
implementation(project(":layer_3:module_3_352"))
implementation(project(":layer_3:module_3_274"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_321"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_397"))
implementation(project(":layer_3:module_3_291"))
implementation(project(":layer_3:module_3_381"))
implementation(project(":layer_3:module_3_391"))
          }
