       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_32"))
implementation(project(":layer_0:module_0_44"))
implementation(project(":layer_0:module_0_18"))
implementation(project(":layer_0:module_0_12"))
implementation(project(":layer_0:module_0_72"))
implementation(project(":layer_0:module_0_92"))
implementation(project(":layer_0:module_0_27"))
implementation(project(":layer_0:module_0_82"))
implementation(project(":layer_0:module_0_43"))
implementation(project(":layer_0:module_0_16"))
implementation(project(":layer_0:module_0_9"))
implementation(project(":layer_0:module_0_56"))
implementation(project(":layer_0:module_0_61"))
implementation(project(":layer_0:module_0_26"))
implementation(project(":layer_0:module_0_71"))
implementation(project(":layer_0:module_0_89"))
implementation(project(":layer_0:module_0_85"))
implementation(project(":layer_0:module_0_58"))
implementation(project(":layer_0:module_0_7"))
implementation(project(":layer_0:module_0_54"))
implementation(project(":layer_0:module_0_69"))
implementation(project(":layer_0:module_0_75"))
implementation(project(":layer_0:module_0_68"))
implementation(project(":layer_0:module_0_45"))
implementation(project(":layer_0:module_0_34"))
implementation(project(":layer_0:module_0_17"))
implementation(project(":layer_0:module_0_29"))
implementation(project(":layer_0:module_0_38"))
implementation(project(":layer_0:module_0_6"))
implementation(project(":layer_0:module_0_52"))
implementation(project(":layer_0:module_0_90"))
implementation(project(":layer_0:module_0_77"))
implementation(project(":layer_0:module_0_49"))
implementation(project(":layer_0:module_0_23"))
implementation(project(":layer_0:module_0_55"))
implementation(project(":layer_0:module_0_73"))
implementation(project(":layer_0:module_0_87"))
implementation(project(":layer_0:module_0_94"))
implementation(project(":layer_0:module_0_64"))
implementation(project(":layer_0:module_0_53"))
implementation(project(":layer_0:module_0_46"))
implementation(project(":layer_0:module_0_91"))
implementation(project(":layer_0:module_0_59"))
implementation(project(":layer_0:module_0_30"))
          }
