       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_1:module_1_120"))
implementation(project(":layer_1:module_1_90"))
implementation(project(":layer_1:module_1_130"))
implementation(project(":layer_1:module_1_78"))
implementation(project(":layer_1:module_1_96"))
implementation(project(":layer_1:module_1_68"))
implementation(project(":layer_1:module_1_94"))
implementation(project(":layer_1:module_1_111"))
implementation(project(":layer_1:module_1_122"))
implementation(project(":layer_1:module_1_71"))
implementation(project(":layer_1:module_1_112"))
implementation(project(":layer_1:module_1_118"))
implementation(project(":layer_1:module_1_139"))
implementation(project(":layer_1:module_1_85"))
implementation(project(":layer_1:module_1_83"))
implementation(project(":layer_1:module_1_70"))
implementation(project(":layer_1:module_1_67"))
implementation(project(":layer_1:module_1_97"))
implementation(project(":layer_1:module_1_91"))
implementation(project(":layer_1:module_1_129"))
implementation(project(":layer_1:module_1_88"))
implementation(project(":layer_1:module_1_144"))
implementation(project(":layer_1:module_1_126"))
implementation(project(":layer_1:module_1_77"))
implementation(project(":layer_1:module_1_110"))
implementation(project(":layer_1:module_1_76"))
implementation(project(":layer_1:module_1_123"))
          }
