       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_1:module_1_229"))
implementation(project(":layer_1:module_1_163"))
implementation(project(":layer_1:module_1_226"))
implementation(project(":layer_1:module_1_201"))
implementation(project(":layer_1:module_1_234"))
implementation(project(":layer_1:module_1_194"))
implementation(project(":layer_1:module_1_230"))
implementation(project(":layer_1:module_1_199"))
implementation(project(":layer_1:module_1_195"))
implementation(project(":layer_1:module_1_192"))
implementation(project(":layer_1:module_1_197"))
implementation(project(":layer_1:module_1_160"))
implementation(project(":layer_1:module_1_155"))
implementation(project(":layer_1:module_1_179"))
implementation(project(":layer_1:module_1_172"))
implementation(project(":layer_1:module_1_220"))
implementation(project(":layer_1:module_1_187"))
implementation(project(":layer_1:module_1_97"))
implementation(project(":layer_1:module_1_216"))
implementation(project(":layer_1:module_1_101"))
implementation(project(":layer_1:module_1_198"))
implementation(project(":layer_1:module_1_190"))
implementation(project(":layer_1:module_1_177"))
implementation(project(":layer_1:module_1_170"))
implementation(project(":layer_1:module_1_128"))
implementation(project(":layer_1:module_1_200"))
implementation(project(":layer_1:module_1_139"))
implementation(project(":layer_1:module_1_127"))
implementation(project(":layer_1:module_1_211"))
implementation(project(":layer_1:module_1_162"))
implementation(project(":layer_1:module_1_161"))
implementation(project(":layer_1:module_1_151"))
implementation(project(":layer_1:module_1_202"))
implementation(project(":layer_1:module_1_147"))
implementation(project(":layer_1:module_1_154"))
implementation(project(":layer_1:module_1_227"))
implementation(project(":layer_1:module_1_185"))
implementation(project(":layer_1:module_1_207"))
implementation(project(":layer_1:module_1_107"))
implementation(project(":layer_1:module_1_106"))
implementation(project(":layer_1:module_1_117"))
implementation(project(":layer_1:module_1_118"))
implementation(project(":layer_1:module_1_103"))
implementation(project(":layer_1:module_1_191"))
          }
