       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_1:module_1_126"))
implementation(project(":layer_1:module_1_108"))
implementation(project(":layer_1:module_1_146"))
implementation(project(":layer_1:module_1_241"))
implementation(project(":layer_1:module_1_137"))
implementation(project(":layer_1:module_1_111"))
implementation(project(":layer_1:module_1_187"))
implementation(project(":layer_1:module_1_204"))
implementation(project(":layer_1:module_1_208"))
implementation(project(":layer_1:module_1_159"))
implementation(project(":layer_1:module_1_97"))
implementation(project(":layer_1:module_1_209"))
implementation(project(":layer_1:module_1_210"))
implementation(project(":layer_1:module_1_116"))
implementation(project(":layer_1:module_1_206"))
implementation(project(":layer_1:module_1_223"))
implementation(project(":layer_1:module_1_217"))
implementation(project(":layer_1:module_1_145"))
implementation(project(":layer_1:module_1_238"))
implementation(project(":layer_1:module_1_160"))
implementation(project(":layer_1:module_1_197"))
implementation(project(":layer_1:module_1_136"))
implementation(project(":layer_1:module_1_110"))
implementation(project(":layer_1:module_1_234"))
implementation(project(":layer_1:module_1_211"))
implementation(project(":layer_1:module_1_219"))
implementation(project(":layer_1:module_1_213"))
implementation(project(":layer_1:module_1_235"))
implementation(project(":layer_1:module_1_195"))
implementation(project(":layer_1:module_1_178"))
implementation(project(":layer_1:module_1_225"))
implementation(project(":layer_1:module_1_244"))
implementation(project(":layer_1:module_1_188"))
implementation(project(":layer_1:module_1_174"))
implementation(project(":layer_1:module_1_191"))
implementation(project(":layer_1:module_1_107"))
implementation(project(":layer_1:module_1_167"))
implementation(project(":layer_1:module_1_230"))
implementation(project(":layer_1:module_1_101"))
implementation(project(":layer_1:module_1_147"))
implementation(project(":layer_1:module_1_156"))
implementation(project(":layer_1:module_1_134"))
implementation(project(":layer_1:module_1_182"))
implementation(project(":layer_1:module_1_123"))
implementation(project(":layer_1:module_1_164"))
implementation(project(":layer_1:module_1_96"))
implementation(project(":layer_1:module_1_163"))
implementation(project(":layer_1:module_1_231"))
implementation(project(":layer_1:module_1_144"))
implementation(project(":layer_1:module_1_196"))
implementation(project(":layer_1:module_1_236"))
implementation(project(":layer_1:module_1_115"))
implementation(project(":layer_1:module_1_193"))
implementation(project(":layer_1:module_1_135"))
implementation(project(":layer_1:module_1_172"))
implementation(project(":layer_1:module_1_106"))
implementation(project(":layer_1:module_1_112"))
implementation(project(":layer_1:module_1_158"))
          }
