       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_28"))
implementation(project(":layer_0:module_0_40"))
implementation(project(":layer_0:module_0_30"))
implementation(project(":layer_0:module_0_11"))
implementation(project(":layer_0:module_0_38"))
implementation(project(":layer_0:module_0_37"))
implementation(project(":layer_0:module_0_56"))
implementation(project(":layer_0:module_0_12"))
implementation(project(":layer_0:module_0_45"))
implementation(project(":layer_0:module_0_25"))
implementation(project(":layer_0:module_0_2"))
implementation(project(":layer_0:module_0_47"))
implementation(project(":layer_0:module_0_46"))
implementation(project(":layer_0:module_0_49"))
implementation(project(":layer_0:module_0_55"))
implementation(project(":layer_0:module_0_4"))
implementation(project(":layer_0:module_0_50"))
implementation(project(":layer_0:module_0_18"))
implementation(project(":layer_0:module_0_42"))
implementation(project(":layer_0:module_0_35"))
implementation(project(":layer_0:module_0_23"))
implementation(project(":layer_0:module_0_36"))
implementation(project(":layer_0:module_0_27"))
implementation(project(":layer_0:module_0_29"))
implementation(project(":layer_0:module_0_57"))
implementation(project(":layer_0:module_0_24"))
          }
