       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_7"))
implementation(project(":layer_0:module_0_43"))
implementation(project(":layer_0:module_0_6"))
implementation(project(":layer_0:module_0_54"))
implementation(project(":layer_0:module_0_26"))
implementation(project(":layer_0:module_0_13"))
implementation(project(":layer_0:module_0_16"))
implementation(project(":layer_0:module_0_37"))
implementation(project(":layer_0:module_0_11"))
implementation(project(":layer_0:module_0_52"))
implementation(project(":layer_0:module_0_44"))
implementation(project(":layer_0:module_0_27"))
implementation(project(":layer_0:module_0_55"))
implementation(project(":layer_0:module_0_28"))
implementation(project(":layer_0:module_0_56"))
implementation(project(":layer_0:module_0_19"))
implementation(project(":layer_0:module_0_40"))
implementation(project(":layer_0:module_0_9"))
implementation(project(":layer_0:module_0_41"))
implementation(project(":layer_0:module_0_53"))
implementation(project(":layer_0:module_0_23"))
implementation(project(":layer_0:module_0_35"))
implementation(project(":layer_0:module_0_46"))
implementation(project(":layer_0:module_0_10"))
implementation(project(":layer_0:module_0_31"))
implementation(project(":layer_0:module_0_8"))
implementation(project(":layer_0:module_0_3"))
implementation(project(":layer_0:module_0_45"))
implementation(project(":layer_0:module_0_25"))
implementation(project(":layer_0:module_0_30"))
implementation(project(":layer_0:module_0_33"))
implementation(project(":layer_0:module_0_50"))
          }
