       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_88"))
implementation(project(":layer_0:module_0_12"))
implementation(project(":layer_0:module_0_54"))
implementation(project(":layer_0:module_0_82"))
implementation(project(":layer_0:module_0_44"))
implementation(project(":layer_0:module_0_85"))
implementation(project(":layer_0:module_0_4"))
implementation(project(":layer_0:module_0_62"))
implementation(project(":layer_0:module_0_30"))
implementation(project(":layer_0:module_0_87"))
implementation(project(":layer_0:module_0_2"))
implementation(project(":layer_0:module_0_5"))
implementation(project(":layer_0:module_0_49"))
implementation(project(":layer_0:module_0_86"))
implementation(project(":layer_0:module_0_75"))
implementation(project(":layer_0:module_0_35"))
implementation(project(":layer_0:module_0_21"))
implementation(project(":layer_0:module_0_63"))
implementation(project(":layer_0:module_0_20"))
implementation(project(":layer_0:module_0_84"))
implementation(project(":layer_0:module_0_94"))
implementation(project(":layer_0:module_0_81"))
implementation(project(":layer_0:module_0_46"))
implementation(project(":layer_0:module_0_67"))
implementation(project(":layer_0:module_0_29"))
implementation(project(":layer_0:module_0_31"))
implementation(project(":layer_0:module_0_76"))
implementation(project(":layer_0:module_0_8"))
implementation(project(":layer_0:module_0_38"))
implementation(project(":layer_0:module_0_66"))
implementation(project(":layer_0:module_0_19"))
implementation(project(":layer_0:module_0_22"))
implementation(project(":layer_0:module_0_58"))
implementation(project(":layer_0:module_0_57"))
          }
