       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_384"))
implementation(project(":layer_3:module_3_305"))
implementation(project(":layer_3:module_3_333"))
implementation(project(":layer_3:module_3_361"))
implementation(project(":layer_3:module_3_335"))
implementation(project(":layer_3:module_3_316"))
implementation(project(":layer_3:module_3_286"))
implementation(project(":layer_3:module_3_317"))
implementation(project(":layer_3:module_3_392"))
implementation(project(":layer_3:module_3_353"))
implementation(project(":layer_3:module_3_314"))
implementation(project(":layer_3:module_3_326"))
implementation(project(":layer_3:module_3_358"))
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_311"))
implementation(project(":layer_3:module_3_289"))
implementation(project(":layer_3:module_3_356"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_258"))
implementation(project(":layer_3:module_3_277"))
implementation(project(":layer_3:module_3_368"))
implementation(project(":layer_3:module_3_377"))
implementation(project(":layer_3:module_3_402"))
implementation(project(":layer_3:module_3_359"))
implementation(project(":layer_3:module_3_292"))
implementation(project(":layer_3:module_3_279"))
implementation(project(":layer_3:module_3_387"))
implementation(project(":layer_3:module_3_342"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_364"))
implementation(project(":layer_3:module_3_312"))
implementation(project(":layer_3:module_3_290"))
implementation(project(":layer_3:module_3_391"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_382"))
implementation(project(":layer_3:module_3_380"))
implementation(project(":layer_3:module_3_366"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_307"))
implementation(project(":layer_3:module_3_394"))
implementation(project(":layer_3:module_3_263"))
implementation(project(":layer_3:module_3_296"))
implementation(project(":layer_3:module_3_349"))
implementation(project(":layer_3:module_3_370"))
implementation(project(":layer_3:module_3_339"))
implementation(project(":layer_3:module_3_308"))
implementation(project(":layer_3:module_3_363"))
implementation(project(":layer_3:module_3_367"))
implementation(project(":layer_3:module_3_274"))
implementation(project(":layer_3:module_3_341"))
implementation(project(":layer_3:module_3_372"))
          }
