       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_14"))
implementation(project(":layer_0:module_0_28"))
implementation(project(":layer_0:module_0_42"))
implementation(project(":layer_0:module_0_21"))
implementation(project(":layer_0:module_0_16"))
implementation(project(":layer_0:module_0_12"))
implementation(project(":layer_0:module_0_17"))
implementation(project(":layer_0:module_0_38"))
implementation(project(":layer_0:module_0_33"))
implementation(project(":layer_0:module_0_40"))
implementation(project(":layer_0:module_0_54"))
implementation(project(":layer_0:module_0_13"))
implementation(project(":layer_0:module_0_31"))
implementation(project(":layer_0:module_0_19"))
implementation(project(":layer_0:module_0_30"))
implementation(project(":layer_0:module_0_55"))
implementation(project(":layer_0:module_0_52"))
implementation(project(":layer_0:module_0_10"))
implementation(project(":layer_0:module_0_25"))
implementation(project(":layer_0:module_0_37"))
implementation(project(":layer_0:module_0_18"))
implementation(project(":layer_0:module_0_7"))
implementation(project(":layer_0:module_0_24"))
implementation(project(":layer_0:module_0_6"))
implementation(project(":layer_0:module_0_9"))
implementation(project(":layer_0:module_0_47"))
implementation(project(":layer_0:module_0_27"))
          }
