       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_307"))
implementation(project(":layer_3:module_3_311"))
implementation(project(":layer_3:module_3_309"))
implementation(project(":layer_3:module_3_356"))
implementation(project(":layer_3:module_3_265"))
implementation(project(":layer_3:module_3_361"))
implementation(project(":layer_3:module_3_333"))
implementation(project(":layer_3:module_3_342"))
implementation(project(":layer_3:module_3_332"))
implementation(project(":layer_3:module_3_371"))
implementation(project(":layer_3:module_3_394"))
implementation(project(":layer_3:module_3_256"))
implementation(project(":layer_3:module_3_336"))
implementation(project(":layer_3:module_3_317"))
implementation(project(":layer_3:module_3_288"))
implementation(project(":layer_3:module_3_331"))
implementation(project(":layer_3:module_3_380"))
implementation(project(":layer_3:module_3_258"))
implementation(project(":layer_3:module_3_280"))
implementation(project(":layer_3:module_3_267"))
implementation(project(":layer_3:module_3_395"))
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_262"))
implementation(project(":layer_3:module_3_396"))
implementation(project(":layer_3:module_3_354"))
implementation(project(":layer_3:module_3_384"))
implementation(project(":layer_3:module_3_291"))
implementation(project(":layer_3:module_3_402"))
implementation(project(":layer_3:module_3_385"))
implementation(project(":layer_3:module_3_391"))
implementation(project(":layer_3:module_3_398"))
implementation(project(":layer_3:module_3_257"))
implementation(project(":layer_3:module_3_389"))
implementation(project(":layer_3:module_3_392"))
implementation(project(":layer_3:module_3_330"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_294"))
implementation(project(":layer_3:module_3_297"))
implementation(project(":layer_3:module_3_364"))
implementation(project(":layer_3:module_3_306"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_369"))
implementation(project(":layer_3:module_3_278"))
implementation(project(":layer_3:module_3_285"))
implementation(project(":layer_3:module_3_322"))
implementation(project(":layer_3:module_3_277"))
implementation(project(":layer_3:module_3_272"))
implementation(project(":layer_3:module_3_323"))
implementation(project(":layer_3:module_3_368"))
implementation(project(":layer_3:module_3_387"))
implementation(project(":layer_3:module_3_397"))
implementation(project(":layer_3:module_3_295"))
implementation(project(":layer_3:module_3_355"))
implementation(project(":layer_3:module_3_313"))
implementation(project(":layer_3:module_3_338"))
implementation(project(":layer_3:module_3_266"))
implementation(project(":layer_3:module_3_347"))
implementation(project(":layer_3:module_3_339"))
          }
