       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_373"))
implementation(project(":layer_3:module_3_327"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_286"))
implementation(project(":layer_3:module_3_403"))
implementation(project(":layer_3:module_3_334"))
implementation(project(":layer_3:module_3_375"))
implementation(project(":layer_3:module_3_339"))
implementation(project(":layer_3:module_3_364"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_368"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_268"))
implementation(project(":layer_3:module_3_265"))
implementation(project(":layer_3:module_3_361"))
implementation(project(":layer_3:module_3_263"))
implementation(project(":layer_3:module_3_323"))
implementation(project(":layer_3:module_3_342"))
implementation(project(":layer_3:module_3_281"))
implementation(project(":layer_3:module_3_280"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_333"))
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_271"))
implementation(project(":layer_3:module_3_288"))
implementation(project(":layer_3:module_3_261"))
implementation(project(":layer_3:module_3_369"))
implementation(project(":layer_3:module_3_376"))
implementation(project(":layer_3:module_3_350"))
implementation(project(":layer_3:module_3_381"))
implementation(project(":layer_3:module_3_300"))
implementation(project(":layer_3:module_3_390"))
implementation(project(":layer_3:module_3_404"))
implementation(project(":layer_3:module_3_352"))
implementation(project(":layer_3:module_3_336"))
implementation(project(":layer_3:module_3_273"))
implementation(project(":layer_3:module_3_315"))
implementation(project(":layer_3:module_3_270"))
implementation(project(":layer_3:module_3_314"))
implementation(project(":layer_3:module_3_310"))
implementation(project(":layer_3:module_3_274"))
implementation(project(":layer_3:module_3_357"))
implementation(project(":layer_3:module_3_356"))
implementation(project(":layer_3:module_3_362"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_322"))
implementation(project(":layer_3:module_3_394"))
implementation(project(":layer_3:module_3_267"))
implementation(project(":layer_3:module_3_335"))
implementation(project(":layer_3:module_3_396"))
implementation(project(":layer_3:module_3_289"))
implementation(project(":layer_3:module_3_355"))
implementation(project(":layer_3:module_3_321"))
implementation(project(":layer_3:module_3_341"))
implementation(project(":layer_3:module_3_332"))
implementation(project(":layer_3:module_3_262"))
implementation(project(":layer_3:module_3_266"))
implementation(project(":layer_3:module_3_291"))
implementation(project(":layer_3:module_3_311"))
implementation(project(":layer_3:module_3_256"))
implementation(project(":layer_3:module_3_328"))
implementation(project(":layer_3:module_3_304"))
implementation(project(":layer_3:module_3_293"))
implementation(project(":layer_3:module_3_402"))
implementation(project(":layer_3:module_3_378"))
          }
