       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_313"))
implementation(project(":layer_3:module_3_299"))
implementation(project(":layer_3:module_3_356"))
implementation(project(":layer_3:module_3_370"))
implementation(project(":layer_3:module_3_374"))
implementation(project(":layer_3:module_3_325"))
implementation(project(":layer_3:module_3_397"))
implementation(project(":layer_3:module_3_396"))
implementation(project(":layer_3:module_3_395"))
implementation(project(":layer_3:module_3_355"))
implementation(project(":layer_3:module_3_307"))
implementation(project(":layer_3:module_3_270"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_295"))
implementation(project(":layer_3:module_3_286"))
implementation(project(":layer_3:module_3_394"))
implementation(project(":layer_3:module_3_346"))
implementation(project(":layer_3:module_3_351"))
implementation(project(":layer_3:module_3_343"))
implementation(project(":layer_3:module_3_404"))
implementation(project(":layer_3:module_3_330"))
implementation(project(":layer_3:module_3_265"))
implementation(project(":layer_3:module_3_386"))
implementation(project(":layer_3:module_3_272"))
implementation(project(":layer_3:module_3_377"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_312"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_381"))
implementation(project(":layer_3:module_3_296"))
implementation(project(":layer_3:module_3_268"))
implementation(project(":layer_3:module_3_303"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_342"))
implementation(project(":layer_3:module_3_391"))
implementation(project(":layer_3:module_3_345"))
implementation(project(":layer_3:module_3_294"))
implementation(project(":layer_3:module_3_380"))
implementation(project(":layer_3:module_3_271"))
implementation(project(":layer_3:module_3_334"))
implementation(project(":layer_3:module_3_359"))
implementation(project(":layer_3:module_3_282"))
implementation(project(":layer_3:module_3_376"))
implementation(project(":layer_3:module_3_398"))
implementation(project(":layer_3:module_3_341"))
implementation(project(":layer_3:module_3_323"))
implementation(project(":layer_3:module_3_316"))
implementation(project(":layer_3:module_3_261"))
implementation(project(":layer_3:module_3_335"))
implementation(project(":layer_3:module_3_305"))
implementation(project(":layer_3:module_3_262"))
implementation(project(":layer_3:module_3_319"))
implementation(project(":layer_3:module_3_310"))
implementation(project(":layer_3:module_3_290"))
implementation(project(":layer_3:module_3_256"))
implementation(project(":layer_3:module_3_329"))
          }
