       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_376"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_399"))
implementation(project(":layer_3:module_3_342"))
implementation(project(":layer_3:module_3_385"))
implementation(project(":layer_3:module_3_294"))
implementation(project(":layer_3:module_3_343"))
implementation(project(":layer_3:module_3_310"))
implementation(project(":layer_3:module_3_307"))
implementation(project(":layer_3:module_3_405"))
implementation(project(":layer_3:module_3_339"))
implementation(project(":layer_3:module_3_381"))
implementation(project(":layer_3:module_3_316"))
implementation(project(":layer_3:module_3_262"))
implementation(project(":layer_3:module_3_300"))
implementation(project(":layer_3:module_3_290"))
implementation(project(":layer_3:module_3_275"))
implementation(project(":layer_3:module_3_322"))
implementation(project(":layer_3:module_3_269"))
implementation(project(":layer_3:module_3_401"))
implementation(project(":layer_3:module_3_320"))
implementation(project(":layer_3:module_3_299"))
implementation(project(":layer_3:module_3_280"))
implementation(project(":layer_3:module_3_366"))
implementation(project(":layer_3:module_3_367"))
implementation(project(":layer_3:module_3_309"))
implementation(project(":layer_3:module_3_284"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_333"))
implementation(project(":layer_3:module_3_313"))
implementation(project(":layer_3:module_3_347"))
implementation(project(":layer_3:module_3_295"))
implementation(project(":layer_3:module_3_285"))
implementation(project(":layer_3:module_3_384"))
implementation(project(":layer_3:module_3_338"))
implementation(project(":layer_3:module_3_344"))
implementation(project(":layer_3:module_3_328"))
implementation(project(":layer_3:module_3_386"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_396"))
implementation(project(":layer_3:module_3_308"))
implementation(project(":layer_3:module_3_372"))
          }
