       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_206"))
implementation(project(":layer_3:module_3_243"))
implementation(project(":layer_3:module_3_174"))
implementation(project(":layer_3:module_3_173"))
implementation(project(":layer_3:module_3_221"))
implementation(project(":layer_3:module_3_233"))
implementation(project(":layer_3:module_3_200"))
implementation(project(":layer_3:module_3_163"))
implementation(project(":layer_3:module_3_222"))
implementation(project(":layer_3:module_3_229"))
implementation(project(":layer_3:module_3_165"))
implementation(project(":layer_3:module_3_225"))
implementation(project(":layer_3:module_3_157"))
implementation(project(":layer_3:module_3_158"))
implementation(project(":layer_3:module_3_205"))
implementation(project(":layer_3:module_3_180"))
implementation(project(":layer_3:module_3_238"))
implementation(project(":layer_3:module_3_215"))
implementation(project(":layer_3:module_3_175"))
implementation(project(":layer_3:module_3_187"))
implementation(project(":layer_3:module_3_236"))
implementation(project(":layer_3:module_3_240"))
implementation(project(":layer_3:module_3_210"))
implementation(project(":layer_3:module_3_166"))
implementation(project(":layer_3:module_3_226"))
implementation(project(":layer_3:module_3_159"))
implementation(project(":layer_3:module_3_167"))
implementation(project(":layer_3:module_3_171"))
implementation(project(":layer_3:module_3_218"))
implementation(project(":layer_3:module_3_198"))
implementation(project(":layer_3:module_3_194"))
          }
