       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_1:module_1_119"))
implementation(project(":layer_1:module_1_85"))
implementation(project(":layer_1:module_1_141"))
implementation(project(":layer_1:module_1_137"))
implementation(project(":layer_1:module_1_117"))
implementation(project(":layer_1:module_1_136"))
implementation(project(":layer_1:module_1_139"))
implementation(project(":layer_1:module_1_133"))
implementation(project(":layer_1:module_1_107"))
implementation(project(":layer_1:module_1_126"))
implementation(project(":layer_1:module_1_97"))
implementation(project(":layer_1:module_1_111"))
implementation(project(":layer_1:module_1_142"))
implementation(project(":layer_1:module_1_138"))
implementation(project(":layer_1:module_1_108"))
implementation(project(":layer_1:module_1_103"))
implementation(project(":layer_1:module_1_123"))
implementation(project(":layer_1:module_1_118"))
implementation(project(":layer_1:module_1_110"))
implementation(project(":layer_1:module_1_95"))
implementation(project(":layer_1:module_1_60"))
implementation(project(":layer_1:module_1_143"))
implementation(project(":layer_1:module_1_113"))
implementation(project(":layer_1:module_1_120"))
implementation(project(":layer_1:module_1_127"))
implementation(project(":layer_1:module_1_131"))
implementation(project(":layer_1:module_1_68"))
implementation(project(":layer_1:module_1_83"))
implementation(project(":layer_1:module_1_104"))
implementation(project(":layer_1:module_1_128"))
implementation(project(":layer_1:module_1_62"))
implementation(project(":layer_1:module_1_76"))
implementation(project(":layer_1:module_1_125"))
implementation(project(":layer_1:module_1_58"))
implementation(project(":layer_1:module_1_71"))
implementation(project(":layer_1:module_1_91"))
implementation(project(":layer_1:module_1_135"))
implementation(project(":layer_1:module_1_122"))
implementation(project(":layer_1:module_1_105"))
implementation(project(":layer_1:module_1_100"))
implementation(project(":layer_1:module_1_101"))
implementation(project(":layer_1:module_1_140"))
implementation(project(":layer_1:module_1_88"))
implementation(project(":layer_1:module_1_102"))
implementation(project(":layer_1:module_1_66"))
implementation(project(":layer_1:module_1_67"))
implementation(project(":layer_1:module_1_146"))
implementation(project(":layer_1:module_1_93"))
implementation(project(":layer_1:module_1_82"))
implementation(project(":layer_1:module_1_73"))
implementation(project(":layer_1:module_1_80"))
implementation(project(":layer_1:module_1_69"))
implementation(project(":layer_1:module_1_59"))
implementation(project(":layer_1:module_1_132"))
implementation(project(":layer_1:module_1_130"))
implementation(project(":layer_1:module_1_109"))
implementation(project(":layer_1:module_1_112"))
implementation(project(":layer_1:module_1_115"))
          }
