       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_315"))
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_334"))
implementation(project(":layer_3:module_3_339"))
implementation(project(":layer_3:module_3_305"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_274"))
implementation(project(":layer_3:module_3_355"))
implementation(project(":layer_3:module_3_267"))
implementation(project(":layer_3:module_3_361"))
implementation(project(":layer_3:module_3_256"))
implementation(project(":layer_3:module_3_382"))
implementation(project(":layer_3:module_3_396"))
implementation(project(":layer_3:module_3_270"))
implementation(project(":layer_3:module_3_346"))
implementation(project(":layer_3:module_3_281"))
implementation(project(":layer_3:module_3_280"))
implementation(project(":layer_3:module_3_402"))
implementation(project(":layer_3:module_3_387"))
implementation(project(":layer_3:module_3_360"))
implementation(project(":layer_3:module_3_388"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_268"))
implementation(project(":layer_3:module_3_377"))
implementation(project(":layer_3:module_3_282"))
implementation(project(":layer_3:module_3_326"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_258"))
implementation(project(":layer_3:module_3_366"))
implementation(project(":layer_3:module_3_314"))
implementation(project(":layer_3:module_3_359"))
implementation(project(":layer_3:module_3_313"))
implementation(project(":layer_3:module_3_260"))
implementation(project(":layer_3:module_3_384"))
implementation(project(":layer_3:module_3_374"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_399"))
implementation(project(":layer_3:module_3_375"))
implementation(project(":layer_3:module_3_322"))
implementation(project(":layer_3:module_3_392"))
implementation(project(":layer_3:module_3_316"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_354"))
implementation(project(":layer_3:module_3_394"))
implementation(project(":layer_3:module_3_293"))
implementation(project(":layer_3:module_3_332"))
implementation(project(":layer_3:module_3_324"))
implementation(project(":layer_3:module_3_308"))
implementation(project(":layer_3:module_3_363"))
          }
