       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_337"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_389"))
implementation(project(":layer_3:module_3_361"))
implementation(project(":layer_3:module_3_336"))
implementation(project(":layer_3:module_3_359"))
implementation(project(":layer_3:module_3_289"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_281"))
implementation(project(":layer_3:module_3_356"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_330"))
implementation(project(":layer_3:module_3_403"))
implementation(project(":layer_3:module_3_370"))
implementation(project(":layer_3:module_3_405"))
implementation(project(":layer_3:module_3_392"))
implementation(project(":layer_3:module_3_368"))
implementation(project(":layer_3:module_3_302"))
implementation(project(":layer_3:module_3_286"))
implementation(project(":layer_3:module_3_313"))
implementation(project(":layer_3:module_3_339"))
implementation(project(":layer_3:module_3_288"))
implementation(project(":layer_3:module_3_369"))
implementation(project(":layer_3:module_3_378"))
implementation(project(":layer_3:module_3_342"))
implementation(project(":layer_3:module_3_398"))
implementation(project(":layer_3:module_3_388"))
implementation(project(":layer_3:module_3_267"))
implementation(project(":layer_3:module_3_352"))
implementation(project(":layer_3:module_3_284"))
implementation(project(":layer_3:module_3_265"))
implementation(project(":layer_3:module_3_380"))
implementation(project(":layer_3:module_3_309"))
implementation(project(":layer_3:module_3_319"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_321"))
implementation(project(":layer_3:module_3_279"))
implementation(project(":layer_3:module_3_285"))
implementation(project(":layer_3:module_3_326"))
implementation(project(":layer_3:module_3_353"))
implementation(project(":layer_3:module_3_273"))
implementation(project(":layer_3:module_3_397"))
implementation(project(":layer_3:module_3_391"))
implementation(project(":layer_3:module_3_274"))
implementation(project(":layer_3:module_3_373"))
implementation(project(":layer_3:module_3_362"))
implementation(project(":layer_3:module_3_386"))
implementation(project(":layer_3:module_3_292"))
implementation(project(":layer_3:module_3_320"))
implementation(project(":layer_3:module_3_344"))
implementation(project(":layer_3:module_3_282"))
implementation(project(":layer_3:module_3_311"))
implementation(project(":layer_3:module_3_300"))
implementation(project(":layer_3:module_3_354"))
implementation(project(":layer_3:module_3_315"))
implementation(project(":layer_3:module_3_257"))
implementation(project(":layer_3:module_3_363"))
          }
