       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_5"))
implementation(project(":layer_0:module_0_93"))
implementation(project(":layer_0:module_0_46"))
implementation(project(":layer_0:module_0_76"))
implementation(project(":layer_0:module_0_32"))
implementation(project(":layer_0:module_0_7"))
implementation(project(":layer_0:module_0_50"))
implementation(project(":layer_0:module_0_30"))
implementation(project(":layer_0:module_0_79"))
implementation(project(":layer_0:module_0_15"))
implementation(project(":layer_0:module_0_65"))
implementation(project(":layer_0:module_0_88"))
implementation(project(":layer_0:module_0_72"))
implementation(project(":layer_0:module_0_27"))
implementation(project(":layer_0:module_0_56"))
implementation(project(":layer_0:module_0_39"))
implementation(project(":layer_0:module_0_67"))
implementation(project(":layer_0:module_0_92"))
implementation(project(":layer_0:module_0_38"))
implementation(project(":layer_0:module_0_11"))
implementation(project(":layer_0:module_0_71"))
implementation(project(":layer_0:module_0_31"))
implementation(project(":layer_0:module_0_3"))
implementation(project(":layer_0:module_0_36"))
implementation(project(":layer_0:module_0_1"))
implementation(project(":layer_0:module_0_37"))
implementation(project(":layer_0:module_0_94"))
implementation(project(":layer_0:module_0_29"))
implementation(project(":layer_0:module_0_13"))
implementation(project(":layer_0:module_0_86"))
implementation(project(":layer_0:module_0_66"))
implementation(project(":layer_0:module_0_24"))
implementation(project(":layer_0:module_0_12"))
implementation(project(":layer_0:module_0_43"))
implementation(project(":layer_0:module_0_53"))
implementation(project(":layer_0:module_0_49"))
implementation(project(":layer_0:module_0_84"))
implementation(project(":layer_0:module_0_89"))
implementation(project(":layer_0:module_0_41"))
implementation(project(":layer_0:module_0_20"))
implementation(project(":layer_0:module_0_14"))
implementation(project(":layer_0:module_0_95"))
implementation(project(":layer_0:module_0_25"))
implementation(project(":layer_0:module_0_82"))
implementation(project(":layer_0:module_0_73"))
implementation(project(":layer_0:module_0_54"))
implementation(project(":layer_0:module_0_19"))
implementation(project(":layer_0:module_0_16"))
implementation(project(":layer_0:module_0_58"))
implementation(project(":layer_0:module_0_70"))
implementation(project(":layer_0:module_0_78"))
implementation(project(":layer_0:module_0_42"))
implementation(project(":layer_0:module_0_51"))
implementation(project(":layer_0:module_0_34"))
          }
