       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_7"))
implementation(project(":layer_0:module_0_1"))
implementation(project(":layer_0:module_0_11"))
implementation(project(":layer_0:module_0_73"))
implementation(project(":layer_0:module_0_93"))
implementation(project(":layer_0:module_0_39"))
implementation(project(":layer_0:module_0_57"))
implementation(project(":layer_0:module_0_82"))
implementation(project(":layer_0:module_0_24"))
implementation(project(":layer_0:module_0_92"))
implementation(project(":layer_0:module_0_3"))
implementation(project(":layer_0:module_0_9"))
implementation(project(":layer_0:module_0_17"))
implementation(project(":layer_0:module_0_4"))
implementation(project(":layer_0:module_0_91"))
implementation(project(":layer_0:module_0_63"))
implementation(project(":layer_0:module_0_29"))
implementation(project(":layer_0:module_0_95"))
implementation(project(":layer_0:module_0_66"))
implementation(project(":layer_0:module_0_6"))
implementation(project(":layer_0:module_0_45"))
implementation(project(":layer_0:module_0_60"))
implementation(project(":layer_0:module_0_12"))
implementation(project(":layer_0:module_0_37"))
implementation(project(":layer_0:module_0_44"))
implementation(project(":layer_0:module_0_87"))
implementation(project(":layer_0:module_0_47"))
implementation(project(":layer_0:module_0_49"))
implementation(project(":layer_0:module_0_41"))
implementation(project(":layer_0:module_0_5"))
implementation(project(":layer_0:module_0_52"))
implementation(project(":layer_0:module_0_65"))
implementation(project(":layer_0:module_0_38"))
implementation(project(":layer_0:module_0_53"))
implementation(project(":layer_0:module_0_30"))
implementation(project(":layer_0:module_0_10"))
implementation(project(":layer_0:module_0_83"))
          }
