       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_403"))
implementation(project(":layer_3:module_3_321"))
implementation(project(":layer_3:module_3_257"))
implementation(project(":layer_3:module_3_391"))
implementation(project(":layer_3:module_3_357"))
implementation(project(":layer_3:module_3_268"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_302"))
implementation(project(":layer_3:module_3_279"))
implementation(project(":layer_3:module_3_311"))
implementation(project(":layer_3:module_3_379"))
implementation(project(":layer_3:module_3_388"))
implementation(project(":layer_3:module_3_310"))
implementation(project(":layer_3:module_3_263"))
implementation(project(":layer_3:module_3_356"))
implementation(project(":layer_3:module_3_286"))
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_349"))
implementation(project(":layer_3:module_3_355"))
implementation(project(":layer_3:module_3_275"))
implementation(project(":layer_3:module_3_381"))
implementation(project(":layer_3:module_3_295"))
implementation(project(":layer_3:module_3_303"))
implementation(project(":layer_3:module_3_399"))
implementation(project(":layer_3:module_3_343"))
implementation(project(":layer_3:module_3_385"))
implementation(project(":layer_3:module_3_395"))
implementation(project(":layer_3:module_3_277"))
implementation(project(":layer_3:module_3_369"))
implementation(project(":layer_3:module_3_256"))
implementation(project(":layer_3:module_3_312"))
implementation(project(":layer_3:module_3_299"))
implementation(project(":layer_3:module_3_404"))
implementation(project(":layer_3:module_3_338"))
implementation(project(":layer_3:module_3_350"))
implementation(project(":layer_3:module_3_323"))
implementation(project(":layer_3:module_3_393"))
implementation(project(":layer_3:module_3_380"))
implementation(project(":layer_3:module_3_367"))
          }
