       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_183"))
implementation(project(":layer_3:module_3_232"))
implementation(project(":layer_3:module_3_208"))
implementation(project(":layer_3:module_3_163"))
implementation(project(":layer_3:module_3_221"))
implementation(project(":layer_3:module_3_162"))
implementation(project(":layer_3:module_3_227"))
implementation(project(":layer_3:module_3_192"))
implementation(project(":layer_3:module_3_237"))
implementation(project(":layer_3:module_3_185"))
implementation(project(":layer_3:module_3_240"))
implementation(project(":layer_3:module_3_176"))
implementation(project(":layer_3:module_3_168"))
implementation(project(":layer_3:module_3_188"))
implementation(project(":layer_3:module_3_170"))
implementation(project(":layer_3:module_3_226"))
implementation(project(":layer_3:module_3_218"))
implementation(project(":layer_3:module_3_210"))
implementation(project(":layer_3:module_3_180"))
implementation(project(":layer_3:module_3_228"))
implementation(project(":layer_3:module_3_241"))
implementation(project(":layer_3:module_3_230"))
implementation(project(":layer_3:module_3_214"))
implementation(project(":layer_3:module_3_202"))
implementation(project(":layer_3:module_3_217"))
implementation(project(":layer_3:module_3_205"))
implementation(project(":layer_3:module_3_167"))
implementation(project(":layer_3:module_3_187"))
implementation(project(":layer_3:module_3_156"))
implementation(project(":layer_3:module_3_189"))
implementation(project(":layer_3:module_3_169"))
implementation(project(":layer_3:module_3_212"))
implementation(project(":layer_3:module_3_182"))
implementation(project(":layer_3:module_3_165"))
implementation(project(":layer_3:module_3_164"))
implementation(project(":layer_3:module_3_154"))
implementation(project(":layer_3:module_3_171"))
implementation(project(":layer_3:module_3_174"))
          }
