       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_2"))
implementation(project(":layer_0:module_0_93"))
implementation(project(":layer_0:module_0_88"))
implementation(project(":layer_0:module_0_53"))
implementation(project(":layer_0:module_0_16"))
implementation(project(":layer_0:module_0_73"))
implementation(project(":layer_0:module_0_18"))
implementation(project(":layer_0:module_0_35"))
implementation(project(":layer_0:module_0_59"))
implementation(project(":layer_0:module_0_44"))
implementation(project(":layer_0:module_0_25"))
implementation(project(":layer_0:module_0_45"))
implementation(project(":layer_0:module_0_8"))
implementation(project(":layer_0:module_0_36"))
implementation(project(":layer_0:module_0_65"))
implementation(project(":layer_0:module_0_3"))
implementation(project(":layer_0:module_0_17"))
implementation(project(":layer_0:module_0_82"))
implementation(project(":layer_0:module_0_84"))
implementation(project(":layer_0:module_0_56"))
implementation(project(":layer_0:module_0_76"))
implementation(project(":layer_0:module_0_22"))
implementation(project(":layer_0:module_0_51"))
implementation(project(":layer_0:module_0_78"))
implementation(project(":layer_0:module_0_4"))
implementation(project(":layer_0:module_0_55"))
          }
