       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_381"))
implementation(project(":layer_3:module_3_311"))
implementation(project(":layer_3:module_3_284"))
implementation(project(":layer_3:module_3_277"))
implementation(project(":layer_3:module_3_359"))
implementation(project(":layer_3:module_3_393"))
implementation(project(":layer_3:module_3_279"))
implementation(project(":layer_3:module_3_257"))
implementation(project(":layer_3:module_3_327"))
implementation(project(":layer_3:module_3_271"))
implementation(project(":layer_3:module_3_394"))
implementation(project(":layer_3:module_3_362"))
implementation(project(":layer_3:module_3_363"))
implementation(project(":layer_3:module_3_349"))
implementation(project(":layer_3:module_3_404"))
implementation(project(":layer_3:module_3_303"))
implementation(project(":layer_3:module_3_298"))
implementation(project(":layer_3:module_3_374"))
implementation(project(":layer_3:module_3_351"))
implementation(project(":layer_3:module_3_281"))
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_275"))
implementation(project(":layer_3:module_3_360"))
implementation(project(":layer_3:module_3_283"))
implementation(project(":layer_3:module_3_376"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_369"))
implementation(project(":layer_3:module_3_308"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_263"))
implementation(project(":layer_3:module_3_395"))
implementation(project(":layer_3:module_3_295"))
implementation(project(":layer_3:module_3_320"))
implementation(project(":layer_3:module_3_296"))
implementation(project(":layer_3:module_3_269"))
implementation(project(":layer_3:module_3_402"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_398"))
          }
