       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_379"))
implementation(project(":layer_3:module_3_402"))
implementation(project(":layer_3:module_3_308"))
implementation(project(":layer_3:module_3_286"))
implementation(project(":layer_3:module_3_372"))
implementation(project(":layer_3:module_3_324"))
implementation(project(":layer_3:module_3_306"))
implementation(project(":layer_3:module_3_310"))
implementation(project(":layer_3:module_3_338"))
implementation(project(":layer_3:module_3_309"))
implementation(project(":layer_3:module_3_356"))
implementation(project(":layer_3:module_3_329"))
implementation(project(":layer_3:module_3_323"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_361"))
implementation(project(":layer_3:module_3_393"))
implementation(project(":layer_3:module_3_395"))
implementation(project(":layer_3:module_3_369"))
implementation(project(":layer_3:module_3_274"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_307"))
implementation(project(":layer_3:module_3_378"))
implementation(project(":layer_3:module_3_260"))
implementation(project(":layer_3:module_3_363"))
implementation(project(":layer_3:module_3_354"))
implementation(project(":layer_3:module_3_375"))
implementation(project(":layer_3:module_3_285"))
implementation(project(":layer_3:module_3_327"))
implementation(project(":layer_3:module_3_368"))
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_341"))
implementation(project(":layer_3:module_3_392"))
implementation(project(":layer_3:module_3_384"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_284"))
implementation(project(":layer_3:module_3_396"))
implementation(project(":layer_3:module_3_390"))
implementation(project(":layer_3:module_3_380"))
implementation(project(":layer_3:module_3_370"))
implementation(project(":layer_3:module_3_290"))
implementation(project(":layer_3:module_3_355"))
implementation(project(":layer_3:module_3_313"))
implementation(project(":layer_3:module_3_275"))
implementation(project(":layer_3:module_3_303"))
implementation(project(":layer_3:module_3_335"))
implementation(project(":layer_3:module_3_374"))
implementation(project(":layer_3:module_3_385"))
implementation(project(":layer_3:module_3_272"))
implementation(project(":layer_3:module_3_401"))
implementation(project(":layer_3:module_3_304"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_337"))
implementation(project(":layer_3:module_3_349"))
implementation(project(":layer_3:module_3_270"))
implementation(project(":layer_3:module_3_388"))
          }
