       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_347"))
implementation(project(":layer_3:module_3_269"))
implementation(project(":layer_3:module_3_280"))
implementation(project(":layer_3:module_3_389"))
implementation(project(":layer_3:module_3_292"))
implementation(project(":layer_3:module_3_281"))
implementation(project(":layer_3:module_3_366"))
implementation(project(":layer_3:module_3_373"))
implementation(project(":layer_3:module_3_382"))
implementation(project(":layer_3:module_3_346"))
implementation(project(":layer_3:module_3_399"))
implementation(project(":layer_3:module_3_353"))
implementation(project(":layer_3:module_3_305"))
implementation(project(":layer_3:module_3_326"))
implementation(project(":layer_3:module_3_272"))
implementation(project(":layer_3:module_3_395"))
implementation(project(":layer_3:module_3_387"))
implementation(project(":layer_3:module_3_364"))
implementation(project(":layer_3:module_3_333"))
implementation(project(":layer_3:module_3_329"))
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_359"))
implementation(project(":layer_3:module_3_279"))
implementation(project(":layer_3:module_3_319"))
implementation(project(":layer_3:module_3_258"))
implementation(project(":layer_3:module_3_401"))
implementation(project(":layer_3:module_3_352"))
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_303"))
implementation(project(":layer_3:module_3_405"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_404"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_336"))
implementation(project(":layer_3:module_3_386"))
implementation(project(":layer_3:module_3_298"))
implementation(project(":layer_3:module_3_392"))
implementation(project(":layer_3:module_3_261"))
implementation(project(":layer_3:module_3_324"))
implementation(project(":layer_3:module_3_332"))
implementation(project(":layer_3:module_3_368"))
implementation(project(":layer_3:module_3_388"))
implementation(project(":layer_3:module_3_325"))
implementation(project(":layer_3:module_3_265"))
implementation(project(":layer_3:module_3_363"))
implementation(project(":layer_3:module_3_394"))
implementation(project(":layer_3:module_3_322"))
implementation(project(":layer_3:module_3_338"))
implementation(project(":layer_3:module_3_342"))
          }
