       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_94"))
implementation(project(":layer_0:module_0_17"))
implementation(project(":layer_0:module_0_7"))
implementation(project(":layer_0:module_0_55"))
implementation(project(":layer_0:module_0_21"))
implementation(project(":layer_0:module_0_38"))
implementation(project(":layer_0:module_0_85"))
implementation(project(":layer_0:module_0_23"))
implementation(project(":layer_0:module_0_57"))
implementation(project(":layer_0:module_0_46"))
implementation(project(":layer_0:module_0_10"))
implementation(project(":layer_0:module_0_82"))
implementation(project(":layer_0:module_0_27"))
implementation(project(":layer_0:module_0_34"))
implementation(project(":layer_0:module_0_19"))
implementation(project(":layer_0:module_0_49"))
implementation(project(":layer_0:module_0_87"))
implementation(project(":layer_0:module_0_42"))
implementation(project(":layer_0:module_0_64"))
implementation(project(":layer_0:module_0_40"))
implementation(project(":layer_0:module_0_67"))
implementation(project(":layer_0:module_0_12"))
implementation(project(":layer_0:module_0_22"))
implementation(project(":layer_0:module_0_74"))
implementation(project(":layer_0:module_0_73"))
implementation(project(":layer_0:module_0_9"))
implementation(project(":layer_0:module_0_11"))
implementation(project(":layer_0:module_0_36"))
implementation(project(":layer_0:module_0_35"))
implementation(project(":layer_0:module_0_15"))
implementation(project(":layer_0:module_0_61"))
implementation(project(":layer_0:module_0_70"))
implementation(project(":layer_0:module_0_39"))
          }
