       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_1:module_1_93"))
implementation(project(":layer_1:module_1_117"))
implementation(project(":layer_1:module_1_60"))
implementation(project(":layer_1:module_1_133"))
implementation(project(":layer_1:module_1_88"))
implementation(project(":layer_1:module_1_68"))
implementation(project(":layer_1:module_1_84"))
implementation(project(":layer_1:module_1_122"))
implementation(project(":layer_1:module_1_129"))
implementation(project(":layer_1:module_1_92"))
implementation(project(":layer_1:module_1_120"))
implementation(project(":layer_1:module_1_141"))
implementation(project(":layer_1:module_1_94"))
implementation(project(":layer_1:module_1_143"))
implementation(project(":layer_1:module_1_86"))
implementation(project(":layer_1:module_1_65"))
implementation(project(":layer_1:module_1_142"))
implementation(project(":layer_1:module_1_124"))
implementation(project(":layer_1:module_1_98"))
implementation(project(":layer_1:module_1_115"))
implementation(project(":layer_1:module_1_121"))
implementation(project(":layer_1:module_1_128"))
implementation(project(":layer_1:module_1_77"))
implementation(project(":layer_1:module_1_147"))
implementation(project(":layer_1:module_1_109"))
implementation(project(":layer_1:module_1_139"))
implementation(project(":layer_1:module_1_110"))
implementation(project(":layer_1:module_1_76"))
implementation(project(":layer_1:module_1_85"))
implementation(project(":layer_1:module_1_140"))
implementation(project(":layer_1:module_1_132"))
implementation(project(":layer_1:module_1_134"))
implementation(project(":layer_1:module_1_96"))
implementation(project(":layer_1:module_1_67"))
implementation(project(":layer_1:module_1_59"))
implementation(project(":layer_1:module_1_89"))
implementation(project(":layer_1:module_1_61"))
implementation(project(":layer_1:module_1_75"))
implementation(project(":layer_1:module_1_95"))
implementation(project(":layer_1:module_1_103"))
implementation(project(":layer_1:module_1_130"))
implementation(project(":layer_1:module_1_125"))
implementation(project(":layer_1:module_1_87"))
implementation(project(":layer_1:module_1_107"))
implementation(project(":layer_1:module_1_102"))
implementation(project(":layer_1:module_1_100"))
implementation(project(":layer_1:module_1_66"))
implementation(project(":layer_1:module_1_69"))
implementation(project(":layer_1:module_1_63"))
implementation(project(":layer_1:module_1_62"))
implementation(project(":layer_1:module_1_105"))
implementation(project(":layer_1:module_1_70"))
implementation(project(":layer_1:module_1_104"))
implementation(project(":layer_1:module_1_73"))
implementation(project(":layer_1:module_1_114"))
          }
