       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_295"))
implementation(project(":layer_3:module_3_299"))
implementation(project(":layer_3:module_3_403"))
implementation(project(":layer_3:module_3_377"))
implementation(project(":layer_3:module_3_405"))
implementation(project(":layer_3:module_3_311"))
implementation(project(":layer_3:module_3_330"))
implementation(project(":layer_3:module_3_266"))
implementation(project(":layer_3:module_3_312"))
implementation(project(":layer_3:module_3_332"))
implementation(project(":layer_3:module_3_329"))
implementation(project(":layer_3:module_3_325"))
implementation(project(":layer_3:module_3_371"))
implementation(project(":layer_3:module_3_386"))
implementation(project(":layer_3:module_3_341"))
implementation(project(":layer_3:module_3_333"))
implementation(project(":layer_3:module_3_323"))
implementation(project(":layer_3:module_3_258"))
implementation(project(":layer_3:module_3_272"))
implementation(project(":layer_3:module_3_397"))
implementation(project(":layer_3:module_3_336"))
implementation(project(":layer_3:module_3_338"))
implementation(project(":layer_3:module_3_297"))
implementation(project(":layer_3:module_3_260"))
implementation(project(":layer_3:module_3_286"))
implementation(project(":layer_3:module_3_362"))
implementation(project(":layer_3:module_3_331"))
implementation(project(":layer_3:module_3_373"))
implementation(project(":layer_3:module_3_280"))
implementation(project(":layer_3:module_3_284"))
implementation(project(":layer_3:module_3_364"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_390"))
implementation(project(":layer_3:module_3_382"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_340"))
implementation(project(":layer_3:module_3_393"))
implementation(project(":layer_3:module_3_275"))
implementation(project(":layer_3:module_3_385"))
implementation(project(":layer_3:module_3_273"))
implementation(project(":layer_3:module_3_277"))
implementation(project(":layer_3:module_3_334"))
implementation(project(":layer_3:module_3_292"))
implementation(project(":layer_3:module_3_359"))
implementation(project(":layer_3:module_3_378"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_339"))
implementation(project(":layer_3:module_3_281"))
implementation(project(":layer_3:module_3_321"))
implementation(project(":layer_3:module_3_271"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_357"))
implementation(project(":layer_3:module_3_351"))
implementation(project(":layer_3:module_3_394"))
implementation(project(":layer_3:module_3_346"))
implementation(project(":layer_3:module_3_302"))
implementation(project(":layer_3:module_3_349"))
implementation(project(":layer_3:module_3_267"))
implementation(project(":layer_3:module_3_375"))
implementation(project(":layer_3:module_3_274"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_352"))
implementation(project(":layer_3:module_3_298"))
implementation(project(":layer_3:module_3_360"))
implementation(project(":layer_3:module_3_355"))
          }
