       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_44"))
implementation(project(":layer_0:module_0_86"))
implementation(project(":layer_0:module_0_55"))
implementation(project(":layer_0:module_0_17"))
implementation(project(":layer_0:module_0_70"))
implementation(project(":layer_0:module_0_25"))
implementation(project(":layer_0:module_0_23"))
implementation(project(":layer_0:module_0_21"))
implementation(project(":layer_0:module_0_36"))
implementation(project(":layer_0:module_0_64"))
implementation(project(":layer_0:module_0_15"))
implementation(project(":layer_0:module_0_52"))
implementation(project(":layer_0:module_0_73"))
implementation(project(":layer_0:module_0_72"))
implementation(project(":layer_0:module_0_24"))
implementation(project(":layer_0:module_0_26"))
implementation(project(":layer_0:module_0_22"))
implementation(project(":layer_0:module_0_84"))
implementation(project(":layer_0:module_0_92"))
implementation(project(":layer_0:module_0_82"))
implementation(project(":layer_0:module_0_95"))
implementation(project(":layer_0:module_0_5"))
implementation(project(":layer_0:module_0_50"))
implementation(project(":layer_0:module_0_67"))
implementation(project(":layer_0:module_0_4"))
implementation(project(":layer_0:module_0_6"))
implementation(project(":layer_0:module_0_27"))
implementation(project(":layer_0:module_0_80"))
implementation(project(":layer_0:module_0_8"))
implementation(project(":layer_0:module_0_60"))
implementation(project(":layer_0:module_0_65"))
implementation(project(":layer_0:module_0_1"))
implementation(project(":layer_0:module_0_9"))
implementation(project(":layer_0:module_0_91"))
implementation(project(":layer_0:module_0_62"))
implementation(project(":layer_0:module_0_38"))
implementation(project(":layer_0:module_0_53"))
implementation(project(":layer_0:module_0_41"))
implementation(project(":layer_0:module_0_42"))
implementation(project(":layer_0:module_0_37"))
implementation(project(":layer_0:module_0_16"))
implementation(project(":layer_0:module_0_13"))
implementation(project(":layer_0:module_0_54"))
implementation(project(":layer_0:module_0_87"))
implementation(project(":layer_0:module_0_85"))
implementation(project(":layer_0:module_0_11"))
implementation(project(":layer_0:module_0_33"))
          }
