       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_385"))
implementation(project(":layer_3:module_3_395"))
implementation(project(":layer_3:module_3_378"))
implementation(project(":layer_3:module_3_396"))
implementation(project(":layer_3:module_3_380"))
implementation(project(":layer_3:module_3_355"))
implementation(project(":layer_3:module_3_314"))
implementation(project(":layer_3:module_3_334"))
implementation(project(":layer_3:module_3_307"))
implementation(project(":layer_3:module_3_331"))
implementation(project(":layer_3:module_3_256"))
implementation(project(":layer_3:module_3_367"))
implementation(project(":layer_3:module_3_283"))
implementation(project(":layer_3:module_3_305"))
implementation(project(":layer_3:module_3_310"))
implementation(project(":layer_3:module_3_343"))
implementation(project(":layer_3:module_3_359"))
implementation(project(":layer_3:module_3_291"))
implementation(project(":layer_3:module_3_265"))
implementation(project(":layer_3:module_3_349"))
implementation(project(":layer_3:module_3_403"))
implementation(project(":layer_3:module_3_316"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_341"))
implementation(project(":layer_3:module_3_288"))
implementation(project(":layer_3:module_3_277"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_323"))
implementation(project(":layer_3:module_3_317"))
implementation(project(":layer_3:module_3_267"))
implementation(project(":layer_3:module_3_391"))
implementation(project(":layer_3:module_3_262"))
implementation(project(":layer_3:module_3_399"))
implementation(project(":layer_3:module_3_364"))
implementation(project(":layer_3:module_3_332"))
implementation(project(":layer_3:module_3_339"))
implementation(project(":layer_3:module_3_354"))
implementation(project(":layer_3:module_3_392"))
implementation(project(":layer_3:module_3_320"))
implementation(project(":layer_3:module_3_286"))
implementation(project(":layer_3:module_3_361"))
implementation(project(":layer_3:module_3_304"))
implementation(project(":layer_3:module_3_279"))
implementation(project(":layer_3:module_3_397"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_281"))
implementation(project(":layer_3:module_3_360"))
implementation(project(":layer_3:module_3_303"))
implementation(project(":layer_3:module_3_289"))
implementation(project(":layer_3:module_3_368"))
implementation(project(":layer_3:module_3_328"))
implementation(project(":layer_3:module_3_401"))
implementation(project(":layer_3:module_3_260"))
implementation(project(":layer_3:module_3_379"))
implementation(project(":layer_3:module_3_263"))
          }
