       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_337"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_291"))
implementation(project(":layer_3:module_3_398"))
implementation(project(":layer_3:module_3_288"))
implementation(project(":layer_3:module_3_403"))
implementation(project(":layer_3:module_3_343"))
implementation(project(":layer_3:module_3_384"))
implementation(project(":layer_3:module_3_287"))
implementation(project(":layer_3:module_3_336"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_334"))
implementation(project(":layer_3:module_3_314"))
implementation(project(":layer_3:module_3_367"))
implementation(project(":layer_3:module_3_320"))
implementation(project(":layer_3:module_3_310"))
implementation(project(":layer_3:module_3_269"))
implementation(project(":layer_3:module_3_307"))
implementation(project(":layer_3:module_3_329"))
implementation(project(":layer_3:module_3_356"))
implementation(project(":layer_3:module_3_256"))
implementation(project(":layer_3:module_3_360"))
implementation(project(":layer_3:module_3_278"))
implementation(project(":layer_3:module_3_352"))
implementation(project(":layer_3:module_3_260"))
implementation(project(":layer_3:module_3_378"))
implementation(project(":layer_3:module_3_327"))
implementation(project(":layer_3:module_3_380"))
implementation(project(":layer_3:module_3_289"))
implementation(project(":layer_3:module_3_324"))
          }
