       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_166"))
implementation(project(":layer_3:module_3_192"))
implementation(project(":layer_3:module_3_215"))
implementation(project(":layer_3:module_3_235"))
implementation(project(":layer_3:module_3_179"))
implementation(project(":layer_3:module_3_238"))
implementation(project(":layer_3:module_3_197"))
implementation(project(":layer_3:module_3_240"))
implementation(project(":layer_3:module_3_224"))
implementation(project(":layer_3:module_3_156"))
implementation(project(":layer_3:module_3_174"))
implementation(project(":layer_3:module_3_213"))
implementation(project(":layer_3:module_3_206"))
implementation(project(":layer_3:module_3_209"))
implementation(project(":layer_3:module_3_216"))
implementation(project(":layer_3:module_3_203"))
implementation(project(":layer_3:module_3_243"))
implementation(project(":layer_3:module_3_242"))
implementation(project(":layer_3:module_3_239"))
implementation(project(":layer_3:module_3_154"))
implementation(project(":layer_3:module_3_234"))
implementation(project(":layer_3:module_3_207"))
implementation(project(":layer_3:module_3_204"))
implementation(project(":layer_3:module_3_176"))
implementation(project(":layer_3:module_3_205"))
implementation(project(":layer_3:module_3_228"))
implementation(project(":layer_3:module_3_237"))
implementation(project(":layer_3:module_3_180"))
implementation(project(":layer_3:module_3_193"))
implementation(project(":layer_3:module_3_241"))
implementation(project(":layer_3:module_3_185"))
implementation(project(":layer_3:module_3_168"))
implementation(project(":layer_3:module_3_158"))
implementation(project(":layer_3:module_3_223"))
implementation(project(":layer_3:module_3_225"))
implementation(project(":layer_3:module_3_219"))
implementation(project(":layer_3:module_3_181"))
implementation(project(":layer_3:module_3_196"))
implementation(project(":layer_3:module_3_214"))
implementation(project(":layer_3:module_3_159"))
          }
