       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_211"))
implementation(project(":layer_3:module_3_223"))
implementation(project(":layer_3:module_3_169"))
implementation(project(":layer_3:module_3_213"))
implementation(project(":layer_3:module_3_216"))
implementation(project(":layer_3:module_3_241"))
implementation(project(":layer_3:module_3_226"))
implementation(project(":layer_3:module_3_224"))
implementation(project(":layer_3:module_3_170"))
implementation(project(":layer_3:module_3_215"))
implementation(project(":layer_3:module_3_173"))
implementation(project(":layer_3:module_3_229"))
implementation(project(":layer_3:module_3_236"))
implementation(project(":layer_3:module_3_164"))
implementation(project(":layer_3:module_3_220"))
implementation(project(":layer_3:module_3_217"))
implementation(project(":layer_3:module_3_163"))
implementation(project(":layer_3:module_3_161"))
implementation(project(":layer_3:module_3_154"))
implementation(project(":layer_3:module_3_238"))
implementation(project(":layer_3:module_3_194"))
implementation(project(":layer_3:module_3_171"))
implementation(project(":layer_3:module_3_231"))
implementation(project(":layer_3:module_3_176"))
implementation(project(":layer_3:module_3_155"))
implementation(project(":layer_3:module_3_199"))
implementation(project(":layer_3:module_3_168"))
implementation(project(":layer_3:module_3_175"))
implementation(project(":layer_3:module_3_187"))
implementation(project(":layer_3:module_3_188"))
implementation(project(":layer_3:module_3_227"))
implementation(project(":layer_3:module_3_190"))
implementation(project(":layer_3:module_3_156"))
implementation(project(":layer_3:module_3_158"))
implementation(project(":layer_3:module_3_221"))
implementation(project(":layer_3:module_3_193"))
implementation(project(":layer_3:module_3_218"))
implementation(project(":layer_3:module_3_243"))
implementation(project(":layer_3:module_3_179"))
implementation(project(":layer_3:module_3_212"))
implementation(project(":layer_3:module_3_203"))
implementation(project(":layer_3:module_3_184"))
implementation(project(":layer_3:module_3_192"))
implementation(project(":layer_3:module_3_234"))
implementation(project(":layer_3:module_3_242"))
implementation(project(":layer_3:module_3_172"))
implementation(project(":layer_3:module_3_189"))
implementation(project(":layer_3:module_3_157"))
implementation(project(":layer_3:module_3_166"))
implementation(project(":layer_3:module_3_182"))
implementation(project(":layer_3:module_3_205"))
implementation(project(":layer_3:module_3_183"))
          }
