       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_363"))
implementation(project(":layer_3:module_3_397"))
implementation(project(":layer_3:module_3_383"))
implementation(project(":layer_3:module_3_295"))
implementation(project(":layer_3:module_3_258"))
implementation(project(":layer_3:module_3_344"))
implementation(project(":layer_3:module_3_259"))
implementation(project(":layer_3:module_3_286"))
implementation(project(":layer_3:module_3_310"))
implementation(project(":layer_3:module_3_287"))
implementation(project(":layer_3:module_3_320"))
implementation(project(":layer_3:module_3_366"))
implementation(project(":layer_3:module_3_381"))
implementation(project(":layer_3:module_3_386"))
implementation(project(":layer_3:module_3_282"))
implementation(project(":layer_3:module_3_308"))
implementation(project(":layer_3:module_3_261"))
implementation(project(":layer_3:module_3_321"))
implementation(project(":layer_3:module_3_388"))
implementation(project(":layer_3:module_3_398"))
implementation(project(":layer_3:module_3_279"))
implementation(project(":layer_3:module_3_379"))
implementation(project(":layer_3:module_3_403"))
implementation(project(":layer_3:module_3_323"))
implementation(project(":layer_3:module_3_276"))
implementation(project(":layer_3:module_3_399"))
implementation(project(":layer_3:module_3_365"))
implementation(project(":layer_3:module_3_346"))
implementation(project(":layer_3:module_3_315"))
implementation(project(":layer_3:module_3_335"))
implementation(project(":layer_3:module_3_283"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_400"))
implementation(project(":layer_3:module_3_309"))
implementation(project(":layer_3:module_3_402"))
implementation(project(":layer_3:module_3_373"))
implementation(project(":layer_3:module_3_352"))
implementation(project(":layer_3:module_3_300"))
          }
