       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_293"))
implementation(project(":layer_3:module_3_301"))
implementation(project(":layer_3:module_3_292"))
implementation(project(":layer_3:module_3_393"))
implementation(project(":layer_3:module_3_351"))
implementation(project(":layer_3:module_3_298"))
implementation(project(":layer_3:module_3_286"))
implementation(project(":layer_3:module_3_405"))
implementation(project(":layer_3:module_3_338"))
implementation(project(":layer_3:module_3_270"))
implementation(project(":layer_3:module_3_343"))
implementation(project(":layer_3:module_3_390"))
implementation(project(":layer_3:module_3_322"))
implementation(project(":layer_3:module_3_380"))
implementation(project(":layer_3:module_3_389"))
implementation(project(":layer_3:module_3_354"))
implementation(project(":layer_3:module_3_263"))
implementation(project(":layer_3:module_3_391"))
implementation(project(":layer_3:module_3_287"))
implementation(project(":layer_3:module_3_325"))
implementation(project(":layer_3:module_3_316"))
implementation(project(":layer_3:module_3_379"))
implementation(project(":layer_3:module_3_312"))
implementation(project(":layer_3:module_3_279"))
implementation(project(":layer_3:module_3_352"))
implementation(project(":layer_3:module_3_361"))
implementation(project(":layer_3:module_3_348"))
implementation(project(":layer_3:module_3_387"))
implementation(project(":layer_3:module_3_313"))
implementation(project(":layer_3:module_3_371"))
implementation(project(":layer_3:module_3_295"))
implementation(project(":layer_3:module_3_378"))
implementation(project(":layer_3:module_3_264"))
implementation(project(":layer_3:module_3_395"))
implementation(project(":layer_3:module_3_288"))
implementation(project(":layer_3:module_3_392"))
implementation(project(":layer_3:module_3_272"))
implementation(project(":layer_3:module_3_388"))
implementation(project(":layer_3:module_3_336"))
implementation(project(":layer_3:module_3_278"))
implementation(project(":layer_3:module_3_344"))
implementation(project(":layer_3:module_3_324"))
implementation(project(":layer_3:module_3_308"))
implementation(project(":layer_3:module_3_262"))
implementation(project(":layer_3:module_3_299"))
implementation(project(":layer_3:module_3_319"))
implementation(project(":layer_3:module_3_317"))
implementation(project(":layer_3:module_3_337"))
implementation(project(":layer_3:module_3_285"))
implementation(project(":layer_3:module_3_318"))
implementation(project(":layer_3:module_3_394"))
implementation(project(":layer_3:module_3_359"))
implementation(project(":layer_3:module_3_310"))
implementation(project(":layer_3:module_3_257"))
          }
