       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_3:module_3_195"))
implementation(project(":layer_3:module_3_204"))
implementation(project(":layer_3:module_3_199"))
implementation(project(":layer_3:module_3_206"))
implementation(project(":layer_3:module_3_242"))
implementation(project(":layer_3:module_3_212"))
implementation(project(":layer_3:module_3_241"))
implementation(project(":layer_3:module_3_156"))
implementation(project(":layer_3:module_3_192"))
implementation(project(":layer_3:module_3_179"))
implementation(project(":layer_3:module_3_203"))
implementation(project(":layer_3:module_3_182"))
implementation(project(":layer_3:module_3_158"))
implementation(project(":layer_3:module_3_236"))
implementation(project(":layer_3:module_3_228"))
implementation(project(":layer_3:module_3_217"))
implementation(project(":layer_3:module_3_189"))
implementation(project(":layer_3:module_3_154"))
implementation(project(":layer_3:module_3_155"))
implementation(project(":layer_3:module_3_243"))
implementation(project(":layer_3:module_3_230"))
implementation(project(":layer_3:module_3_161"))
implementation(project(":layer_3:module_3_196"))
implementation(project(":layer_3:module_3_221"))
implementation(project(":layer_3:module_3_209"))
implementation(project(":layer_3:module_3_216"))
implementation(project(":layer_3:module_3_215"))
implementation(project(":layer_3:module_3_164"))
implementation(project(":layer_3:module_3_208"))
implementation(project(":layer_3:module_3_227"))
implementation(project(":layer_3:module_3_218"))
implementation(project(":layer_3:module_3_157"))
implementation(project(":layer_3:module_3_169"))
implementation(project(":layer_3:module_3_173"))
implementation(project(":layer_3:module_3_200"))
implementation(project(":layer_3:module_3_207"))
implementation(project(":layer_3:module_3_205"))
implementation(project(":layer_3:module_3_175"))
          }
