       plugins {
          id ("java-library")
          id ("maven-publish")
          id ("jacoco")
          id ("org.sonarqube") version "4.3.0.3225"
          id("awesome.kotlin.plugin")
       }
          dependencies {
             
implementation(project(":layer_0:module_0_5"))
implementation(project(":layer_0:module_0_63"))
implementation(project(":layer_0:module_0_88"))
implementation(project(":layer_0:module_0_80"))
implementation(project(":layer_0:module_0_32"))
implementation(project(":layer_0:module_0_31"))
implementation(project(":layer_0:module_0_34"))
implementation(project(":layer_0:module_0_47"))
implementation(project(":layer_0:module_0_57"))
implementation(project(":layer_0:module_0_41"))
implementation(project(":layer_0:module_0_74"))
implementation(project(":layer_0:module_0_90"))
implementation(project(":layer_0:module_0_76"))
implementation(project(":layer_0:module_0_56"))
implementation(project(":layer_0:module_0_23"))
implementation(project(":layer_0:module_0_14"))
implementation(project(":layer_0:module_0_46"))
implementation(project(":layer_0:module_0_1"))
implementation(project(":layer_0:module_0_54"))
implementation(project(":layer_0:module_0_87"))
implementation(project(":layer_0:module_0_52"))
implementation(project(":layer_0:module_0_48"))
implementation(project(":layer_0:module_0_19"))
implementation(project(":layer_0:module_0_42"))
implementation(project(":layer_0:module_0_85"))
implementation(project(":layer_0:module_0_49"))
implementation(project(":layer_0:module_0_21"))
implementation(project(":layer_0:module_0_92"))
implementation(project(":layer_0:module_0_68"))
implementation(project(":layer_0:module_0_15"))
implementation(project(":layer_0:module_0_62"))
implementation(project(":layer_0:module_0_18"))
implementation(project(":layer_0:module_0_16"))
implementation(project(":layer_0:module_0_95"))
implementation(project(":layer_0:module_0_36"))
implementation(project(":layer_0:module_0_72"))
implementation(project(":layer_0:module_0_67"))
implementation(project(":layer_0:module_0_66"))
implementation(project(":layer_0:module_0_78"))
implementation(project(":layer_0:module_0_24"))
implementation(project(":layer_0:module_0_35"))
implementation(project(":layer_0:module_0_81"))
implementation(project(":layer_0:module_0_9"))
implementation(project(":layer_0:module_0_11"))
implementation(project(":layer_0:module_0_59"))
implementation(project(":layer_0:module_0_60"))
implementation(project(":layer_0:module_0_53"))
          }
